### ISSUE TITLE
Получать список TMS с сервера

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#10]
Выложить где-то на сервере (например, nextgis.ru) список TMS в виде json:
```json
[
   {"name" : "osm",
   "url" : "http://{a,b,c}.tiles.openstreetmap.org/{z}/{x}/{y}.png"
   },
   {"name" : "kosmosnimki",
   "url" : "http://{a,b,c,d}.tiles.kosmosnimki.ru/{z}/{x}/{y}.png"
   }
]
```
В диалоге сделать 2 вкладки "Список", "Ручной ввод". Если список не получен, выводить только ручной ввод или кэшировать список.

**Comment by drnextgis** [comment]
А почему именно на сервере, может проще такой список распространять вместе с приложением?

**Comment by BishopGIS** [comment]
Тут вопрос на 2 части делится: 
1. Более простое обновление этого списка
2. "Политический" момент. Когда если там в списке вдруг окажется ресурс который правообладатель потребует удалить, что бы не перевыкладывать приложение в маркет, а просто список обновить на сервачке.
Тем более TMS работает только при наличии интернета, так что получить копеешный файл с сервера я думаю не проблема.

**Comment by drnextgis** [comment]
Можно брать список подложек из QMS.

**Comment by simgislab** [comment]
Я думаю вообще что наша вполне успешная затея с QMS должна превратиться в централизованный способ получать, добавлять и шарить подложки вообще в любом ПО. Чтобы можно было получать подложки и из мобильного и из НГВ и т.д.

**Comment by 4eRTuk** [comment]
В свете QMS закрываю тикет.
