### ISSUE TITLE
Создание точки касанием по экрану

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#100]

**Comment by 4eRTuk** [comment]
Куда это добавить? Иконкой в боттомбар при редактировании точечного слоя?

**Comment by BishopGIS** [comment]
Я думал по длинному клику добавлять. Это можно сделать добавив иконку в панель операций:
http://docs.nextgis.ru/docs_ngmobile/source/main.html#ngmobile-selectmode-pic
А далее при наличии нескольких слоев типа точка-мультиточка - показывать диалог выбора (http://docs.nextgis.ru/docs_ngmobile/source/editing.html#ngmobile-select-layer-dialog-pic), иначе брать первый слой, добавлять в него точку и показывать интерфейс редактирования:
http://docs.nextgis.ru/docs_ngmobile/source/editing.html#id7 но сразу должна быть дискета в левом углу, а не галка.
