### ISSUE TITLE
Поддержка элемента "официальная" подпись

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#101]

**Comment by BishopGIS** [comment]
Сам контрол для снятия подписи сделан. У контрола можно запросить картинку подписи сохранить во вложении (например, со стандартным именем sing.png).
Но вот надо определится с дальнейшим поаведением: что делать когда форма открывается повторно? Затирать старую подпись или не давать менять и показывать картинку старой подписи?

**Comment by 4eRTuk** [comment]
Думаю показывать старую подпись и отдельная иконка для замены существующей. Показывать и не менять стоит только в атрибутах.

**Comment by BishopGIS** [comment]
Иконка замены подписи есть в контроле подписи. Так что осталось добить показ.
