### ISSUE TITLE
Информационные сообщения

### ISSUE THREAD

**Issue by taimyr** [nextgis/android_gisapp#106]
1) при загрузке некорректного (или битого) тайлового архива выводится сообщение, не проясняющее причин сбоя, ну то что нет причин - еще ладно, но оно (сообщение) висит несколько секунд и исчезает...
2) Если при загрузке большого тайлового архива ненамеренно "тапнуть" карту, этот "прогресс-бар" исчезает, что неудобно.
Предлагаю эти и им подобные окна держать в фоне и сделать "явное" закрытие.

**Comment by BishopGIS** [comment]
Сообщения теперь висят долго.
Саму загрузку слоя можно перевести в фон, что бы случайно не закрыть диалог.
