### ISSUE TITLE
Не работает панель редактирования текста

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#11]
В полях с именем и URL при создании TMS слоя. При двойном тапе должна появиться панель в которой можно выбрать инструмент Вырезать (по крайней мере в Chrome так), а у нас появляется панель с одной галкой, которая не понятно что означает.

**Comment by simgislab** [comment]
у меня вот так, ты про это?

![](https://www.dropbox.com/s/gp8ii9jl6iap0jj/Screenshot_2014-12-29-13-56-24.png?dl=0)

**Comment by drnextgis** [comment]
Да, про это, только у меня вот так выглядит:
![screenshot_2015-01-31-21-50-44](https://cloud.githubusercontent.com/assets/866124/5988648/21ee1434-a98b-11e4-8ff5-83da2d7fb767.png)

**Comment by BishopGIS** [comment]
У меня как у Дениса. Только вставить.

**Comment by drnextgis** [comment]
В полях, где задаётся подключение к NGW, работает как надо.

**Comment by BishopGIS** [comment]
Там отличие в том что подключение открывается в отдельном активити, а ТМС в
диалоге.

**Comment by drnextgis** [comment]
Такая же нерабочая панель в окне "Create vector layer", когда открываешь локальный файл.
