### ISSUE TITLE
При перемещении карты оверлей текущего местоположения хаотично перемещается по экрану

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/android_gisapp#116]
При перемещении карты оверлей текущего местоположения хаотично перемещается по экрану. По окончании перерисовки карты возвращается на место.

**Comment by NikitaFeodonit** [comment]
Тестировал с текущими коммитами, собрав свою сборку.

**Comment by BishopGIS** [comment]
У кого ни будь еще воспроизводится?

**Comment by NikitaFeodonit** [comment]
Проявляется также при изменении масштаба карты двойным щелчком по карте.

**Comment by NikitaFeodonit** [comment]
После пересборки пока поймать не смог.
