### ISSUE TITLE
При уменьшении масштаба пальцами повисает перерисовка

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/android_gisapp#117]
Область карты при уменьшении пальцами уменьшается, по краям появляется фоновый рисунок и на этом так и остается, пока не сдвинуть карту.

**Comment by BishopGIS** [comment]
А кнопкой пересисовки карты если (та что рядом с центрированием)?

**Comment by NikitaFeodonit** [comment]
> А кнопкой пересисовки карты если (та что рядом с центрированием)?

Не понял, о какой кнопке речь. 

Если кнопками "+/-", то ими поймать пока не смог.

Если такой эффект возник, то при нажатии на кнопку "Найти" (справа от кнопки добавления векторных слоев), для перемещения центра карты на текущее местоположение, карта также не перерисовывается. Так и остается уменьшенная область карты с фоновым рисунком по краям.

**Comment by BishopGIS** [comment]
![screenshot_2015-04-02-17-50-15](https://cloud.githubusercontent.com/assets/1708122/7144350/a45c7dde-e2ed-11e4-9326-a8988def0ba3.png)

**Comment by NikitaFeodonit** [comment]
После полной пересборки (debug) и переустановки на аппарате пока поймать не смог.
