### ISSUE TITLE
При создании полигона обходом возможность остановить и продолжить обход

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#126]

**Comment by BishopGIS** [comment]
Сделал несколько иначе. При обходе появляется кнопка карандаша, по которой можно отредактировать другой слой не завершая процесс обхода. 
Кроме того, сейчас можно изменить имеющуюся геометрию обходом (в интерфейсе пока не реализовано).

**Comment by simgislab** [comment]
переоткрываю, так как непонятно работает ли оно

**Comment by BishopGIS** [comment]
Вот это не правильно. Если не работает - тогда и переоткрывай. А то так можно любой тикет переоткрыть.

**Comment by simgislab** [comment]
но мы же уже обсудили, что карандаш - не работает

**Comment by simgislab** [comment]
как "остановить и продолжить", то же не ясно

т.е. оно может в коде и работает даже, но ни одной возможности проверить пока я не вижу

В общем я бы переоткрыл, но теперь боюсь, сам давай, если согласен)

**Comment by BishopGIS** [comment]
Это вообще о другом. Про карандаш вот тут написано  #284

**Comment by BishopGIS** [comment]
А про вопрос, как остановить и продолжить вот тикет  #283 
Т.е. после создания геометрии обходом, ее или другую иную, всегда можно будет изменить.
