### ISSUE TITLE
Добавить индикацию неактивных кнопок редактирования

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#127]
Например, кнопки `Добавить точку`, если не выбрана мультиточка.

**Comment by BishopGIS** [comment]
Еще менять цвет кнопки записи трека, что бы в интерфейсе было понятно, что трек пишется.

**Comment by simgislab** [comment]
еще удобно добавлять небольшую красную точку к иконке для индикации того же

**Comment by 4eRTuk** [comment]
Предлагаю сделать панель как на скриншоте в #295. Это довольно удобно и очевидно на мой взгляд.

**Comment by BishopGIS** [comment]
Там вопрос про другое. Например панель редактирования мультиполигона:
http://docs.nextgis.ru/docs_ngmobile/source/editing.html#ngmobile-toolbar-mpolyg-pic

И кнопка удаления кольца неактивна, потому что кольцо не выделено. Но этого не понятно.

**Comment by 4eRTuk** [comment]
Да, я понял. Кнопка Redo на скриншоте неактивна - вполне понятно.

**Comment by BishopGIS** [comment]
Да, хороший вариант. Главное, что бы видно было.
