### ISSUE TITLE
Не показывать фразу про синхронизацию и кнопку в drawer, если нет подключений к NGW

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#128]
В 2.1 она ничего не означает, как я понимаю.

**Comment by BishopGIS** [comment]
Так и есть. Удали все подключения к НГВ и переустанови полностью приложение. Ни фразы, ни кнопки не будет.

**Comment by simgislab** [comment]
а почему просто после удаления подключения к НГВ не убирается фраза?

**Comment by BishopGIS** [comment]
Видимо баг. А кнопка исчезла?

**Comment by simgislab** [comment]
нет
