### ISSUE TITLE
не валидная геометрия при создании полигонов 

### ISSUE THREAD

**Issue by RuslanKiselev** [nextgis/android_gisapp#129]
Создали форму с полигонами, отрисовали парочку на карте. Экспортировали в Geojsom. Не сохраняется в постгис, так как не валидная геометрия.

**Comment by simgislab** [comment]
Не знаю про формы, но полигон я создавал сам по себе, экспортируется и открывается в кугисе нормально. Видимо неплохо бы приложить набор данных?

**Comment by BishopGIS** [comment]
Там ключевое слово PostGIS - у него более строгая проверка валидности. Я думаю, что там первая и последняя точки не дублируются и в этом ошибка.
