### ISSUE TITLE
Белый текст на сером  фоне  в меню

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#134]
![screenshot_2015-05-09-09-27-53](https://cloud.githubusercontent.com/assets/866124/7548503/6f77abde-f625-11e4-9c1f-71a12d43e1bc.png)

**Comment by BishopGIS** [comment]
Похоже, что это системная проблема. 
У меня пока в эмуляторе такое только воспроизводится. А вот на реальном устройстве меню черное, текст белый, при этом в подменю наборот - фон белый, текст черный.
http://stackoverflow.com/q/14192761

Могу предложить 2 варианта:
1. забить и ждать как гугл починит
2. заблокировать меню кнопке - при клике на кнопку будет открываться верхнее меню (http://stackoverflow.com/a/10220312).

http://developer.android.com/training/keyboard-input/commands.html
http://stackoverflow.com/a/29852304

**Comment by drnextgis** [comment]
В последней версии проблема больше не наблюдается.

**Comment by BishopGIS** [comment]
Тогда закрываю
