### ISSUE TITLE
Нет возможности добавить слой из NGW

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#135]
Выбираю `Добавить слой`, а там только `Локальный` и `Веб`.

**Comment by simgislab** [comment]
все правильно, в текущей бете эта возможность отключена

**Comment by drnextgis** [comment]
Тогда, наверное, стоит отключить и возможность создания подключения к NGW.

**Comment by BishopGIS** [comment]
Это лишняя работа, которая в 2.2 нужно будет возвращать обратно. А менюшку  спрятать гораздо проще.
