### ISSUE TITLE
Предлагаю убрать подписи к кнопкам

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#138]
Предлагаю убрать подписи к кнопкам "Добавить объект" и т.п, выглядят они очень топорно и портят общее впечатление от в целом довольно красиво выглядящего приложения. Назначение кнопок можно описать в документации, все равно в приложении всё не подпишешь.

**Comment by BishopGIS** [comment]
Чего-то обсуждали в скайпе, к чему пришли непонятно.

**Comment by simgislab** [comment]
предлагаю пока не дергаться с этим, согласен, что выглядит не очень, но лучше сосредоточиться на багах и вернуться к этому в 2.2

**Comment by simgislab** [comment]
убираем подписи
