### ISSUE TITLE
Не определяется положение по gps

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#139]
Привет. Такая проблема с мобильным. Интернета нет, включил gps, нажал locate me, ждал минут 10 - андроид пишет поиск спутников. Надоело ждать, включил приложение 2ГИС, тот нашел спутники в течении нескольких секунд. Включаю обратно наше приложение, опять жму locate me, отображается маркер моего положения, но тайлов нет, так как я без Интернета. Все ничего, но спустя несколько секунд маркер исчезает с экрана, в тулбаре андроида появляется значок поиска спутников - покрутится секунд 10, пропадет, опять появится  и так бесконечно. Маркер с моим местоположением больше не появляется, если опять не переключиться  на 2гис, но потом по описанной схеме опять исчезает  с экрана. В настройках  определения местоположения - gps и сотовая связь.

**Comment by BishopGIS** [comment]
Да, подтверждаю. Такая же проблема.

**Comment by 4eRTuk** [comment]
Думаю дело в том, что мы ограничили минимум спутников для фикса - 3. Баг на улице наблюдается?

**Comment by BishopGIS** [comment]
Нет, не в этом проблема. Прямо сейчас на улице стоял минут 10 - не ловит фикс и все тут. Да и до этого такое было. Причем, часто как только обнаруживает Wi-Fi - то фикс по GPS теряет (вернее не теряет, а переключается на Wi-Fi).

**Comment by drnextgis** [comment]
У меня проблема больше не наблюдается. Закрываем?

**Comment by BishopGIS** [comment]
Fix in ca18f3fba1d30d9ac281372d365fd24c39c909bc
