### ISSUE TITLE
Возможность удаления подключения к NGW

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#14]

**Comment by BishopGIS** [comment]
Вообще-то имеется. Как через настройки самой программы - см. последний
пункт в самом аккаунте, после настройки синхронизации. Так и через
системные настройки, там это в меню запрятано.

**Comment by drnextgis** [comment]
В меню нашёл, а что за настройки синхронизации, они где?

**Comment by BishopGIS** [comment]
![screenshot_2015-02-01-14-03-49_f](https://cloud.githubusercontent.com/assets/1708122/5991870/6e96d330-aa1b-11e4-87a3-1fbcdeb4b2ba.png)

**Comment by drnextgis** [comment]
Я не могу найти такое окно.

**Comment by BishopGIS** [comment]
Зайти в меню settings, выбрать NextGIS Web, выбрать любой созданный аккаунт, откроется диалог его настроек.
settings -> NextGIS Web -> <account name>
