### ISSUE TITLE
Более точное детектирование наличие Интернет

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#140]
При движении по городу программа постоянно подключается к разным сетям Wi-Fi и пытается через них качать тайлы. Каждый такл - это таймаут несколько секунд. Предлагаю, при первом сбойном тайле - TIMEOUT - выставлять флаг на минуту, что интернета нет. И повторять попытку через этот период времени, пока тайлы будут получаться из локального кеша. Ставить вот в этом классе https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/util/NetworkUtil.java#L82

**Comment by 4eRTuk** [comment]
А если в кеше нет нужного тайла и подряд несколько тайлов? Будет очень большое ожидание.

**Comment by BishopGIS** [comment]
Как раз наоборот. Сейчас на каждом тайле (правда в 2 потока) происходит ожидание,  равное TIMEOUT (например 16 тайлов = 8 * TIMEOUT времени будет ожидание). А так, при первом сбое, будет помечаться, что ресурс недоступен, например, в течении пары минут, уже не будет попыток доступа и все тайлы будут сразу в кеше искаться.

**Comment by 4eRTuk** [comment]
Тут еще надо учесть, что isNetworkAvailable() не только в классе TMS слоя используется.

**Comment by BishopGIS** [comment]
Да, это я вначале хотел для всех так сделать - сейчас думаю лучше в рамках одного слоя. А то какой ни будь ресурс уйдет в down, а мобилка подумает что интернета нет.
