### ISSUE TITLE
Иногда не закрывается сессия записи трека

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#141]
Точно не помню. Раньше вроде открывалось приложение, теперь только шторка закрывается. 
Видимо это специфичный баг моей конфигурации. Google Nexus 4.4.4

**Comment by BishopGIS** [comment]
В общем проблема была в следующем:
Я записывал трек когда ехал на метро на открытом участке. 
При въезде в туннель из-за бессмысленности выключил запись. При этом что-то в БД не записалось и трек значился все время как бы записывающимся (это в соответствии с запросом: String selection = TrackLayer.FIELD_END + " IS NULL OR " + TrackLayer.FIELD_END + " = ''" возвращался курсор с  данными).
Из за этого не стартовала запись трека (т.е. уведомление появлялось, но ничего не происходило) и не работала кнопка "открыть".
Каким образом кнопка открыть связана с самим статусом записи - я не понял.

**Comment by simgislab** [comment]
не понял какой вывод, ставлю на 2.2

**Comment by BishopGIS** [comment]
Я бы подождал фидбека. пока только это было у меня. Пока не будет сообщений от других пользователей, я бы не занимался этим.
