### ISSUE TITLE
Make drawer icons different for layers with different geometry types

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#144]
right now they are the same independently of geom type.

**Comment by carto-lab** [comment]
maybe icon for layer should be same as symbol for layer?

![icons](https://cloud.githubusercontent.com/assets/5606648/7752003/cda608b2-ffe5-11e4-891d-bd908c0c60dc.png)

**Comment by simgislab** [comment]
great idea

**Comment by 4eRTuk** [comment]
Where from we can get proper symbol for each specific layer?

**Comment by BishopGIS** [comment]
We have to draw them the same way as in map. Create little canvas and draw - for polygon layer - rectangle, for linestring layer - line, etc. Also the little icon of sync state needed (if layer syncable).

**Comment by 4eRTuk** [comment]
Should this be applied to ngw vector layers to?

**Comment by BishopGIS** [comment]
All vector layers. The sync state icon only for NGW layer. There is one problem. As the closer to implement switch dark/light interface, this symbology may be hard to see in some theme.
The some standard icon for polygon, line and point is more usable in such case. What is preferable?
May be we need a set of icons - standard + symbology?

**Comment by simgislab** [comment]
good source of icons: http://thenounproject.com, only color should be changed as I see it

**Comment by 4eRTuk** [comment]
We already have a lot of icons for bottom edit bar. Maybe we could use these icons just without specific details (plus sign, X-delete)? Of course color overlay will be there.

**Comment by simgislab** [comment]
let's see how it looks like

**Comment by 4eRTuk** [comment]
Something like this 
https://www.dropbox.com/s/gff09hr8l9rl17i/ic_type_line.png?dl=0
https://www.dropbox.com/s/k7lkftp8rhl6fz6/ic_type_polygon.png?dl=0

**Comment by simgislab** [comment]
works for me
