### ISSUE TITLE
Кнопка "Обновить" - Действие при клике

### ISSUE THREAD

**Issue by carto-lab** [nextgis/android_gisapp#154]
При нажатии на кнопку "Обновить карту" в верхнем меню инструментов  (являющуюся одновременно и индикатором загрузки данных) ничего не происходит. Как минимум нужна анимация вращения при клике. Плюс можно добавить сообщение "Карта обновлена" или другое похожее.

**Comment by BishopGIS** [comment]
Вообще-то она должна вращаться. Видимо данных не много и экран обновился очень быстро. А если переместить на территорию, где тайлы подложки не прокачаны, что происходит? Или вы подложку отключили?

**Comment by carto-lab** [comment]
При перемещении - прокачке тайлов - вращается.

> Видимо данных не много и экран обновился очень быстро.
Может в этом случае как-то "принудительно" добавить вращение? чтобы какой-то отклик видеть по действию

**Comment by BishopGIS** [comment]
Добавил тикет #164
