### ISSUE TITLE
Кнопка "Обновить координаты точки" - Действие при клике

### ISSUE THREAD

**Issue by carto-lab** [nextgis/android_gisapp#155]
Панель инструментов "Добавить > Добавить текущую точку". При нажатии на серую кнопку справа "Обновить координаты" - нет анимации/сообщения. Можно добавить анимацию на кнопку для наглядности и/или сообщение.

**Comment by BishopGIS** [comment]
Да, согласен. Поставил отметку как "улучшение". Добавим такой функционал.

**Comment by BishopGIS** [comment]
Fix in cc93181846ce1749d9a419abc6e42acb4932b993
