### ISSUE TITLE
Добавить настроек отображения для векторного слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#157]
В диалог настроек векторного слоя добавить настройки отображения геометрий согласно типу геометрии, а также выбор рендерера.

**Comment by 4eRTuk** [comment]
Какие настройки должны отображаться? Для точек тип маркера, а для линий/полигонов?

**Comment by BishopGIS** [comment]
Все должно зависеть от выбранного рендеррера слоя (да и выбор рендерера в виде выпадающего списка было бы неплохо добавить). 
Там же разные могут быть настройки. Посмотри, может какую-то функцию добавить к https://github.com/nextgis/android_maplib/blob/ebfee18473f84103631924eb2849b40c139cb6f0/src/main/java/com/nextgis/maplib/api/IRenderer.java - getProperties или типа того.

**Comment by 4eRTuk** [comment]
А какие еще рендереры для векторных слоев есть? Я вижу только SimpleFeatureRenderer и RuleFeatureRenderer, который нигде не используется.

**Comment by NikitaFeodonit** [comment]
RuleFeatureRenderer используется в Компулинке и в инспекторе для рисования объектов в соответствии с их свойствами (построен, не построен, какой тип и т.п.).

**Comment by BishopGIS** [comment]
Не используется, потому что в интерфейс не вынесено переключение рендерера слоя.

**Comment by 4eRTuk** [comment]
Не очень представляю, как его в NGM использовать. Надо тогда отдельное окно делать для соотнесения свойств объектов и настроек для этого рендерера.

**Comment by BishopGIS** [comment]
Там по аналогии с QGIS. 
Но идея, что рендеры могут добавляться и соответственно разработчик не должен изменять этот диалог. 
Я обычно это делаю через интерфейсы. В интерфейсах есть обязательные методы, которые надо закодить. Например, метод, возвращающий активити настроек. 
А окно настроек, просто запрашивает этот метод у текущего выбранного ренедрера. 
Видимо это должно быть в  maplibui.

**Comment by 4eRTuk** [comment]
See #63 also

**Comment by 4eRTuk** [comment]
Посмотрел RuleFeatureRenderer - как понял, для каждого объекта согласно его id можно задать свой стиль. Мне кажется слишком сложно для простого пользователя, да и нужно все Renderer и Style тогда переносить в maplibui. Обязательно ли это в 2.4?

**Comment by BishopGIS** [comment]
render и style переносить не нужно - только сделать renderUI и styleUI при необходимости.
Вообще все настройки стилей - это для продвинутых пользователей, которые туда полезут. У нас довольно мало непродвинутых сейчас.

**Comment by BishopGIS** [comment]
Не учтены стили:
* https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/SimpleTiledPolygonStyle.java
* https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/SimpleTextPolygonStyle.java
* https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/SimpleTextMarkerStyle.java
* https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/display/SimpleTextLineStyle.java
