### ISSUE TITLE
При первом изменении формата вывода координат нет индикации текущего значения

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#158]
![2015-05-21 13 33 20](https://cloud.githubusercontent.com/assets/1708122/7746797/030fb232-ffbe-11e4-9764-e4ac50814f69.png)

**Comment by BishopGIS** [comment]
На текущей версии у меня не воспроизводится. Может кто-то проверить?

**Comment by NikitaFeodonit** [comment]
У меня последний коммит от [29.07.2015](https://github.com/nextgis/android_gisapp/commit/2a7edf2619beed3eb32128ef724be8697b3c995c).

У меня не воспроизводится. Отчистил все данные приложения, запустил как бы первый раз. Сразу показало выбранным значение DD.DDDD.

**Comment by BishopGIS** [comment]
Ну считаем, что исправлено
