### ISSUE TITLE
Изменить название пункта в настройке минимального времени обновления

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#159]
«Ноль» выглядит не совсем привычно. Можно заменить на тескт «мин.доступное»,
«минимальное», или «так часто, как возможно» (как в меню выше уровнем).
![2015-05-21 13 36 24](https://cloud.githubusercontent.com/assets/1708122/7746854/664da66a-ffbe-11e4-9407-3897737d1fac.png)

**Comment by simgislab** [comment]
может "Наиболее часто"
