### ISSUE TITLE
Изменить заголовок диалога при добавлении слоя TMS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#160]
«Создать» можно заменить на «Добавить»
![2015-05-21 13 39 56](https://cloud.githubusercontent.com/assets/1708122/7746926/fcf74120-ffbe-11e4-9f39-94006efa7540.png)

**Comment by simgislab** [comment]
пофиксил https://github.com/nextgis/android_maplibui/commit/bf4274e11135b22933ca039ea3af843e8aa32825
