### ISSUE TITLE
Диалог выхода из программы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#162]
Есть предложение:
"При клике правой аппаратной кнопки происходит выход из программы. Возможно имеет смысл
добавить меню подтверждения действия – «Выйти и программы Да/Нет»."

Меня такое обычно сильно раздражает. Тем более охват и иная информация по текущему сеансу корректно сохраняется.
Вопрос: стоит ли делать такое уведомление или сделать с отключением в настройках?

**Comment by 4eRTuk** [comment]
Может сделать всплывающее сообщение аля "Нажмите назад еще раз чтобы выйти"? Не так навязчиво как диалог.

**Comment by simgislab** [comment]
поддерживаю предложение Стаса

**Comment by BishopGIS** [comment]
Завел тикет #163
