### ISSUE TITLE
Выпадающий список с поиском по первым буквам

### ISSUE THREAD

**Issue by carto-lab** [nextgis/android_gisapp#165]
Добавить возможность ввода данных (текст) в виде выпадающего списка с поиском по первым буквам.

На этапе заполнения атрибутов, при вводе первых букв отображаются доступные значения начинающиеся на эти буквы. При добавлении следующих букв слова число вариантов сокращается. Варианты доступных значений задаются на этапе создания формы. Удобно в случае выбора из доступных значений числом 20 и более шт. Например, при регистрации видов растений.

enhancement

**Comment by BishopGIS** [comment]
Это немного дублирует вот этот тикет: #54
Т.е. суть в том, что в следующем релизе для слоя можно будет разработать свою форму, хоть со списком, хоть с радиокнопками.
Правда в списке не было поиска при вводе - поэтому, этот тикет не закрываю. 
Но в стандартном диалоге редактирования атрибутов такого делать не будем.

**Comment by carto-lab** [comment]
Да, здесь ключевое - поиск по буквам для ускорения выбора из десятков возможных значений

**Comment by simgislab** [comment]
на стороне Formbuilder соответствующая галка появилась: https://github.com/nextgis/formbuilder/issues/53

**Comment by 4eRTuk** [comment]
Может ли быть введено и сохранено значение не из списка?

**Comment by BishopGIS** [comment]
Должна быть какая-то настройка по выбору редактируемый список или нет.

**Comment by simgislab** [comment]
добавил запрос на параметр в https://github.com/nextgis/formbuilder/issues/53
