### ISSUE TITLE
Порядок векторных слоев в меню

### ISSUE THREAD

**Issue by carto-lab** [nextgis/android_gisapp#166]
Сейчас порядок векторных слоев отличается 1) в меню основной панели по управлению видимостью и порядком слоев и 2) в меню выбора слоя для редактирования. Такие различия могут смущать недостаточно опытного полевого работника. Можно попробовать отображать одинаковый порядок, если реализуемо, либо отдельно оговорить этот момент в документации.

**Comment by BishopGIS** [comment]
Да, думаю порядок должен совпадать.
