### ISSUE TITLE
Общий кэш подложек для различных мобильных приложений NGM

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/android_gisapp#168]
Каждое приложение на базе NGM (NGM, Metrocell, Compulink) имеет свой собственный кэш TMS.
Это приводит к тому, что на устройстве лежат три копии москвы или другой территории. 
Разделяемый кэш позволил бы экономить место и пользоваться прокаченным кэшем из любого аппа.

**Comment by BishopGIS** [comment]
Fix in https://github.com/nextgis/nextgis_datastore/ will be available in NGM3
