### ISSUE TITLE
Keep screen on не работает

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#17]
Экран всё равно отключается.

**Comment by BishopGIS** [comment]
У меня не воспроизводится. Опция работает только в окне карты. Если открыта иное окно приложения - оно будет выключаться.

**Comment by drnextgis** [comment]
Да, я про окно карты.

**Comment by drnextgis** [comment]
Если запустить приложение с включенным данным пунктом, то он работает, а если запустить с отключенным, а потом включить, то не работает.

**Comment by simgislab** [comment]
Подтверждаю

1. запустил приложение
2. включил галку
3. вернулся в окно карты
-> экран потух

**Comment by 4eRTuk** [comment]
Исправлено.
