### ISSUE TITLE
Настройка фона карты по-умолчанию

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#170]
Дать возможность выбора цвета фона в настройках приложения:
* светлый
* темный 
* нейтральный

**Comment by 4eRTuk** [comment]
Опять же, есть какие-то варианты? Или просто затемнить/осветлить текущую?

**Comment by BishopGIS** [comment]
Давай просто серый квадрат 10% (типа белый) и 80% (типа темный)? а наш оставим и назовем "нейтральным".

**Comment by 4eRTuk** [comment]
Сделал 25%, 10 слишком темный.
