### ISSUE TITLE
Отображать панель информации при редактировании

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#176]
Сейчас панель скрывается при редактировании и восстанавливается при завершении редактирования. Нужна настройка, что бы этого не просиходило.

**Comment by simgislab** [comment]
Keep status bar open

**Comment by 4eRTuk** [comment]
Может вынести в список "Скрыть / Показывать при просмотре карты / Показывать всегда"? Будет одна настройка вместо двух.

**Comment by BishopGIS** [comment]
Хорошая идея
