### ISSUE TITLE
Добавить в диалог идентификации данные о геометрии

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#177]
В диалоге идентификации отображать для:
* точек - координаты
* линий - длину
* полигонов - периметр и площадь

**Comment by 4eRTuk** [comment]
А для мультигеометрий как?

**Comment by BishopGIS** [comment]
Для мультиточек, центр. Для остальных все также:
мультилинии - общая длина и мультиполигон - общая площмдь и общая длина

**Comment by 4eRTuk** [comment]
Для полигонов учитывать дырки в площади?

**Comment by BishopGIS** [comment]
Да, но там просто. Считаешь площадь дырки и отнимаешь от общей площади.
