### ISSUE TITLE
Индикация загрузки слоев NGW

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#18]
Некоторые слои появляются тут же, а некоторые не сразу (либо загружаются долго, либо отрисовываются) и не понятно, то ли что-то происходит не так, либо что нужно просто подождать.

**Comment by BishopGIS** [comment]
Нужна поддержка со стороны НГВ: https://github.com/nextgis/nextgisweb/issues/375

**Comment by drnextgis** [comment]
Необходимый функционал добавлен.

**Comment by BishopGIS** [comment]
Индикация реализована. Сейчас есть и диалог и в статусе прогресс.

**Comment by simgislab** [comment]
речь же только про векторные слои?

**Comment by BishopGIS** [comment]
Нет. Растровый кэш в zip тоже. А остальные типы слоёв ничего не грузят
сразу.
