### ISSUE TITLE
Freehand drawing

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#180]
При рисовании линий и полигонов добавить такой способ ввода

**Comment by 4eRTuk** [comment]
Как она должна работать?

**Comment by BishopGIS** [comment]
Аналогично тому, как у нас рисуется подпись. Т.е. пользователь ведет пальцем/стилусом по экрану. Через заданные промежутки ставятся точки. В зависимости от типа фигуры (линия или полигон) рисуется незамкнутое или замкнутое.

**Comment by 4eRTuk** [comment]
Куда поместить кнопку? В панель редактирования геометрии?

**Comment by BishopGIS** [comment]
Да, вот сюда: http://docs.nextgis.ru/docs_ngmobile/source/editing.html#ngmobile-map-window-edit-mode-ml-pic в самый конец. Если в контекстное меню уйдет - не беда.
