### ISSUE TITLE
Не добавляется GeoJSON, если в поле id не-число

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#185]
![screenshot_2015-05-29-13-22-41](https://cloud.githubusercontent.com/assets/4630662/7881008/70560e1e-0607-11e5-8a97-b073c4f9f5a5.png)

Шаги для повторения:
Зайти на overpass-turbo.eu - юг Москвы
Ввести запрос на точки входов в здания:

```
[out:json][timeout:25];
// gather results
(
  // query part for: “entrance=*”
  node["entrance"]({{bbox}});
  way["entrance"]({{bbox}});
  relation["entrance"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
`````
Сохранить как geojson

**Comment by trolleway** [comment]
![screenshot_2015-05-29-16-46-41](https://cloud.githubusercontent.com/assets/4630662/7884162/9920982e-0624-11e5-9198-72bd9226666a.png)
![screenshot_2015-05-29-17-01-43](https://cloud.githubusercontent.com/assets/4630662/7884168/9ddfb84a-0624-11e5-9f04-09235b1daec1.png)

**Comment by BishopGIS** [comment]
Fix in c75053cb69738bd19c96d6017dcc009b6c2eb651
