### ISSUE TITLE
Крэш приложения при открытии слоя NGW

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#187]
Открыл один из слоёв, но он не отрисовывается, через какое-то время приложение вылетает.

**Comment by BishopGIS** [comment]
Уж больно данных много - твое устройство не может их в памяти умевстить. Отсюда: java.lang.OutOfMemoryError
Надо в сторону потокового парсера json смотреть.

**Comment by simgislab** [comment]
может какое-то предупреждение выводить?

**Comment by BishopGIS** [comment]
Не лучшая идея, т.к. у нас в фоне еще происходиб обмен инфомрации. А там сообщение не выведешь.
Вот вполне решение: http://developer.android.com/reference/android/util/JsonReader.html
Проблема только в том, что там с API 11, а у нас минимальное 8.
Возможно есть альтернативы.

**Comment by drnextgis** [comment]
У нас есть какая-то необходимость в поддержке старых API?

**Comment by BishopGIS** [comment]
Я думаю, что пока - да. В маркете 5% таких установок + РЛЗ. Но это не самая киллер фича (SAX JSON Reader), чтобы не найти под необходимый API.

**Comment by BishopGIS** [comment]
Fixed in https://github.com/nextgis/android_maplib/commit/c3888e640f81b71d7ec958b37281a8190faef221
