### ISSUE TITLE
Куда-то пропал пункт Raster возле одного слоя

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#19]
![screenshot_2015-02-01-21-46-06](https://cloud.githubusercontent.com/assets/866124/5992661/d9c26236-aa53-11e4-87dc-7bdc7f203606.png)

**Comment by BishopGIS** [comment]
Так и задумано. У этого слоя нет стиля, поэтому его нельзя отобразить как растр.

**Comment by drnextgis** [comment]
Ещё раз подключился - появился.

**Comment by BishopGIS** [comment]
И это тоже нормально. Значит либо из-за связи либо из-за НГВ не были переданы стили. У меня сейчас стоит таймаут 7 секунд. Причем мы планируем вынести эту настройку в свойства приложения, что бы под свой канал можно было подстроиться.

**Comment by simgislab** [comment]
не пойму в итоге, это баг-репорт или обсуждение

**Comment by BishopGIS** [comment]
Надо проверить на новой сборке, когда будет интеграция с НГВ - не раньше 2.3.

**Comment by BishopGIS** [comment]
Проверьте на текущей сборке воспроизводится?

**Comment by simgislab** [comment]
у меня не воспроизводится, у всех векторных слоев в этой группе есть по две галки

demo.nextgis.ru/rekod/file set test/import 3
