### ISSUE TITLE
Включить в состав приложения кэш ОСМ с 0 по 3 (4,5...) уровень

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#194]
В презентациях говорим, что кэш живёт 7 дней - а оказывается по умолчанию его нет, даже у дефолтного слоя OSM.

**Comment by BishopGIS** [comment]
Сейчас в составе приложения имеются 3 векторных слоя. Необходимо дополнительно добавить еще кэш ОСМ с 0 и по какой-то уровень. Исходить следует из размера АПК файла

**Comment by simgislab** [comment]
получился явный костыль, который не решает задачу наличия данных ОСМ первых уровней в любой момент времени, сразу после установки нужно заходить в приложение, ждать пока оно загрузит первые уровни ОСМ...не говоря уже о том что приложение может быть установлено из APK без интернета

нужно определить допустимый объем данных и внедрить их прямо в пакет

**Comment by BishopGIS** [comment]
Хотелось бы конкретики какие уровни зума необходимо включить в пакет. А то какая-то расплывчатая задача.

**Comment by simgislab** [comment]
А это просто.

Пусть @trolleway скажет сколько весит 1,2,3,4 уровень данных OSM, из этого и решить.

**Comment by BishopGIS** [comment]
Так на всякий случай - у меня на планшете минимальный уровень зума 5-й. Т.е. если в апк будет зашито 0-4 - то эти тайлы не будут использоваться - только место занимать.

**Comment by simgislab** [comment]
>Так на всякий случай - у меня на планшете минимальный уровень зума 5-й.
Почему так? У тебя какой-то особенный планшет? У меня на телефоне вроде при старте 1й уровень.

**Comment by BishopGIS** [comment]
1, но не 0-й. Минимальный зум выбирается таким образом, что бы полюса не помещались в карту. Это сделано по ряду причин:
1. Что бы не было видно фона при любом уровне зума (как сделано в Гуглокартах). Всегда есть вертикальный скролл
2. На очень мелких зумах не работает матрица перехода между экранными и географическими координатами). Предполагаюю из-за точности float.

**Comment by simgislab** [comment]
@trolleway посчитай плиз объемы данных на 0-5 уровне

**Comment by BishopGIS** [comment]
@trolleway @drnextgis давал скрипт для выкачивания ОСМ - нужно выкачать с 0 - 5 и сказать сколько весит.

**Comment by trolleway** [comment]
0..4 1.2M
0..5 4.0M
0..6 15.2М

**Comment by simgislab** [comment]
ну вот 0-5 и включить

**Comment by simgislab** [comment]
@trolleway, плиз пошли тайлы на эти уровни @4eRTuk
