### ISSUE TITLE
Добавить в настройки возможность возврата приложения в состояние по-умолчанию

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#196]
В состоянии по-умолчанию удаляются все слои и восстанавливаются 3 векторных слоя и слой ОСМ.

**Comment by 4eRTuk** [comment]
Настройка влияет только на слои?

**Comment by BishopGIS** [comment]
Нет, еще очень важно - вернуть путь до карты в исходное. 
А по хорошему и галки и всякие цифры (типа показа контролов зума и времени снятия координат). Вот что делать не надо - это удалять аккаунты. Они н6е совсем фишка приложения.
