### ISSUE TITLE
Переключение между светлым и темным интерфейсом

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#197]
В светлом нужны более темные тулбары.

**Comment by 4eRTuk** [comment]
Насколько темные? Есть какие-то приблизительные варианты?

Переключение тем уже работает.

**Comment by simgislab** [comment]
голубые шапки не переключаются, поэтому сейчас выглядит странновато

**Comment by BishopGIS** [comment]
Так и задумано. Меняются только диалоги, окна, списки, контролы редактирования. Тулбары не трогаем.

**Comment by simgislab** [comment]
но выглядит странновато, прямо скажем

**Comment by BishopGIS** [comment]
Примеры программ с переключением интерфейса в студию. У меня таких парочка и обе именно так делают (https://play.google.com/store/apps/details?id=com.textra&hl=ru и https://play.google.com/store/apps/details?id=com.seazon.feedme&hl=ru). 
В конце концов возьми графический редактор и скриншот мобильного и покрась как считаешь должно быть. Посмотрим как у тебя получится "не странно".

**Comment by simgislab** [comment]
ну хотя бы потемнее шапку можно делать? на первом скриншоте они потемнее вроде в темной теме

**Comment by BishopGIS** [comment]
Сделать можно все что угодно. Вопрос сколько это займет времени. И опять же - нужны hex коды для цветов приложения для темной темы, иконки и т.п.:
основной цвет, акцент цвет, дополнительный цвет, а также цвета текста в тулбарах и иконки - светлые или темные.
Вот например цвета тулбара https://github.com/nextgis/android_maplibui/blob/master/src/main/res/values/colors.xml#L45-L50  
цвет текста https://github.com/nextgis/android_maplibui/blob/master/src/main/res/values/colors.xml#L52-L56
иконки которые придется переделывать (не все в этих папках но многие):
https://github.com/nextgis/android_maplibui/tree/master/src/main/res/drawable-hdpi
https://github.com/nextgis/android_maplibui/tree/master/src/main/res/drawable-mdpi
https://github.com/nextgis/android_maplibui/tree/master/src/main/res/drawable-xhdpi
https://github.com/nextgis/android_maplibui/tree/master/src/main/res/drawable-xxhdpi

И я не понял - почему надо делать темнее? Обычно все делают как раз светлее - что бы было контрастнее.

**Comment by simgislab** [comment]
решили пока не менять
