### ISSUE TITLE
При удалении слоя сделать отмену действия

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#2]
При удалении слоя во всплывающем окне (Toast) сделать кнопку отмена. Само удаление слоя сделать отложенным, чтобы можно было отменить это действие.
![index](https://cloud.githubusercontent.com/assets/1708122/5915328/8f57ed3e-a615-11e4-8adb-846fdea3bfaa.jpeg)

**Comment by simgislab** [comment]
При удалении слоя в панели отмены сейчас пишет "Объект удален", можно писать "Слой удален"?
