### ISSUE TITLE
Выбросы при записи обходом

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#200]
Даже при установке всех настроек в GPS only все равно возникают выбросы.
На скриншотах в фоне видны выбросы (см. тикет #198)

**Comment by 4eRTuk** [comment]
Исходя из записанных треков, все выбросы - это точки без высоты. Возможно, каким-то образом цепляется NETWORK_PROVIDER или GPS_PROVIDER отдает совсем неточный фикс (это может быть из-за прекращения работы наземных GPS станций - санкции). Предлагаю отсекать такие точки, если указан источник "Только GPS".

**Comment by BishopGIS** [comment]
Было бы неплохо подебажить точно ли не цепляется NETWORK_PROVIDER (там же у Loaction есть источник). Если цепляется - то это надо исправить. А вот если нет - тогда уже можно отбрасывать.
