### ISSUE TITLE
Текст Toolbar'а в окне настроек черный, стилями не управляется

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/android_gisapp#201]
Проблема в этом баге:
https://code.google.com/p/android/issues/detail?id=175559

Пока откачу версию appcompat обратно на 22.1.1

**Comment by NikitaFeodonit** [comment]
Оставлю открытым, чтобы следить за тем багом. Как исправят, то и тут закроем.

**Comment by BishopGIS** [comment]
Окно настроек наследуется от PrefernceActivity который не AppCompatActivity поэтому там со стилями плохо. Что касательно самого тулбара который добавляется довольно хитро в коде, то это исправлено https://github.com/nextgis/android_maplibui/commit/d00bea40f6d669dfc940204d54b0c6b29f127236
