### ISSUE TITLE
Синхронизацию выполнять через одно удерживаемое подключение к серверу

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/android_gisapp#202]
Предлагаю во время синхронизации не открывать заново подключение к серверу и закрывать на каждый слой, а использовать для всех слоев одно удерживаемое подключение, закрываемое по окончании синхронизации. Это подключение использовать и для получения изменений с сервера и для отправки изменений на сервер.

По моему, есть вероятность, что может значительно сократить время синхронизации.

**Comment by BishopGIS** [comment]
Я сейчас переделал для > Android 3 на потоковую синхронизацию и sax. Возможно этого будет достаточно. Как такового открытия соединения нет, т.к. все идет через Basic HTTP Auth. Это в библиотеке сделано как будто что-то там открывается и закрывается. На самом деле просто формируется запрос и нет разницы используется ли для запроса один HTTPGet или разные.

**Comment by BishopGIS** [comment]
Актуально? Я бы закрыл этот тикет.
