### ISSUE TITLE
Разграничить permissions

### ISSUE THREAD

**Issue by 4eRTuk** [nextgis/android_gisapp#205]
Вынести все необходимые для работы библиотек permissions из основного manifest в соответствующие manifest библиотек.

**Comment by BishopGIS** [comment]
Я наоборот поубирал пермишены из библиотек - что бы в прилоджении которое их использует указывать. Не во всех приложениях нужны все пермишены библиотеки.

**Comment by BishopGIS** [comment]
Актуально? Я бы закрыл этот тикет.
