### ISSUE TITLE
Settings: turn off geolocation

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#209]
Add setting to turn off geolocation completely, no circles, no marker on the map, no GPS acquisition and energy consumption

**Comment by BishopGIS** [comment]
Ты об этом?
![screenshot_2015-09-13-20-05-08](https://cloud.githubusercontent.com/assets/1708122/9837926/fa371d68-5a57-11e5-96a6-a679a75661b3.png)

**Comment by simgislab** [comment]
а если сказать "не показывать", то оно и гпс не будет дергать?

**Comment by BishopGIS** [comment]
Там еще для треков GPS дергается и для постановки текущего местоположения. А так - да.

**Comment by simgislab** [comment]
'Do not show current location' should turn off GPS for everything except for tracks?

**Comment by 4eRTuk** [comment]
I think no. You could turn off GPS in system settings for everything.

**Comment by simgislab** [comment]
ok, closing as won't fix for now
