### ISSUE TITLE
Выводить подсказку при отсутствии подходящего слоя

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#21]
Если нет векторных слоёв, то при нажатии на кнопку добавления объекта выводится сообщение "There is no editable layers", если мы открываем локальный файл, например, geojson  - то при нажатии на кнопку ничего не происходит и никаких подсказок не выводится.

**Comment by BishopGIS** [comment]
Это на баг похоже, хотя скорее всего просто не сделано.

**Comment by drnextgis** [comment]
Проверил, все работает хорошо.
