### ISSUE TITLE
No undo panel when deleting a feature in a edit mode

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#217]
undo panel disappeared in latest build, bug?

**Comment by 4eRTuk** [comment]
Do you mean undo for deletion? Everything should work, code wasn't changed.

**Comment by simgislab** [comment]
I remember there was an undo panel appearing for few seconds in a lower part of the screen in 2.1, but I can't reproduce it anyhow no matter how hard I try.

**Comment by 4eRTuk** [comment]
What steps do you follow? Undo panel should appears only after deleteing feature.

**Comment by simgislab** [comment]
1. Start editing a layer
2. Create a polygon
3. Delete it -> no Undo

**Comment by 4eRTuk** [comment]
There was no undo panel in edit mode in 2.1, only in select feature mode.

**Comment by 4eRTuk** [comment]
Do we need undo for deletion in edit mode? X button discards changes anyway, it's like undo. Or maybe we should create custom panel with undo/redo for any edit actions. Something like this http://prntscr.com/8iqchv

**Comment by simgislab** [comment]
yep, this is open for discussion, but as Undo is working, let's put it away for later releases, definitely not for 2.2, 2.3

**Comment by 4eRTuk** [comment]
#68
