### ISSUE TITLE
Два окна при быстром нажатии кнопки создания объекта

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#22]
Если быстро нажать два раза на кнопке добавления объекта, то появляется 2 окна с выбором слоя (если доступных слоёв больше 1) друг поверх друга.

**Comment by BishopGIS** [comment]
И в чем проблема? Или один из диалогов не рабочий? 
Если ты делаешь double click наверное тебе нужно больше диалогов?

**Comment by drnextgis** [comment]
Нет, больше диалогов не нужно, просто можно сделать, чтобы дополнительных окон не появлялось, они ведь явно не предусмотрены?

**Comment by BishopGIS** [comment]
Один щелчок - один диалог. Второй щелчок - второй диалог и т.д. 
Зачем вводить искусственное ограничение на количество диалогов? Тут скорее, что бы его ввести придется выдумывать.

**Comment by simgislab** [comment]
мне кажется, что много диалоговых окон это неправильно
