### ISSUE TITLE
Some attributes missing in geojson

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#220]
How to reproduce:
* Go to http://overpass-turbo.eu. Use this query
```
[out:json][timeout:25];
// gather results
(
  // query part for: “building=*”
  way["building"]({{bbox}});
  relation["building"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```
* Run, and export as geojson some area around office.
* Open geojson in NextGIS Mobile

Current behavior: 
There is no any attributes in mobile app except building=*

Expected behavior:
there should be all attributes from geojson.

**Comment by trolleway** [comment]
![2015-09-24 15 27 43](https://cloud.githubusercontent.com/assets/4630662/10073394/326dcb9c-62d1-11e5-869e-c7d847906cd3.png)
![screenshot_2015-09-24-15-28-38](https://cloud.githubusercontent.com/assets/4630662/10073397/383d420a-62d1-11e5-9d9d-a4d8d3a623d8.png)

**Comment by BishopGIS** [comment]
As we use sax json parser we create the table using the first feature attributes. In you case the features have different set of attributes. The sqlite in Android didn't support alter new fields. So there is only way to have all attributes - to preprocess your geojson such way to present all attributes in all features before loading into NGM.

**Comment by BishopGIS** [comment]
Sorry. There is a way to add new column
http://stackoverflow.com/questions/8291673/how-to-add-new-column-to-android-sqlite-database

So accepted the bug
