### ISSUE TITLE
При создании фото из формы в приложении фотография сохраняется с поворотом на 90 градусов

### ISSUE THREAD

**Issue by RuslanKiselev** [nextgis/android_gisapp#224]

**Comment by trolleway** [comment]
Попробовал повторить на Lenovo A2010. Фотографии снимаемые в вертикальной ориентации добавляются, а в горизонтальной ориентации - не добавляются.

**Comment by 4eRTuk** [comment]
@RuslanKiselev а попробуй другое приложение камеру. В коде никаких поворотов нет.

**Comment by 4eRTuk** [comment]
@trolleway починено

**Comment by BishopGIS** [comment]
Возможно как-то обрабатывается тэг в EXIF в снимке. Тоже попробую потестировать.

**Comment by BishopGIS** [comment]
У меня все ок

**Comment by BishopGIS** [comment]
maybe: http://www.droidnews.ru/google_o_fotografiyah_vverh_nogami_na_nexus_5x

**Comment by BishopGIS** [comment]
Мне кажется в какой-то момент перестало проявляться. Надо проверить

**Comment by 4eRTuk** [comment]
@RuslanKiselev у тебя воспроизводится? попробуй другую приложение-камеру установить, будет ли с ней воспроизводиться.
