### ISSUE TITLE
'Required' flag for a text edit control makes 'numbers flag' invalid

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#230]
Suppose there are two text edit controls.

Number 1 has both 'requred' and 'only numbers' flags raised.
Number 2 has only 'only numbers' flag raised.

Start editing form.

Current - you can enter text in Number 1 and you can't in Number 2
Expected - both fields should except only numbers.

Example for testing: https://www.dropbox.com/s/6kv94nmw0npk9v1/fb-test5.ngfp?dl=0

**Comment by 4eRTuk** [comment]
Problem was in JSON field type: "text" is string type. We were handling only integer and real fields in edit form screen. Now text edits accept only integers for string fields if "only numbers" flag raised.
