### ISSUE TITLE
Не редактируется PostGIS

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#234]
При добавлении на карту слоя PostGIS и попытке его отредактировать пишет что нет редактируемых слоёв.

**Comment by BishopGIS** [comment]
У нас мультилинии и мультиполигоны для редактирования не поддерживаются (#49 и #51). А есть точечный слой из PostGIS для проверки?

**Comment by drnextgis** [comment]
Посмотрю. Но по тапу появляется панель с карандашом - или это отдельный тикет?

**Comment by BishopGIS** [comment]
Это нормальное поведение. Там же кроме карандаша есть еще атрибуты и удалить. Просто в оверлее редактирования если геометрия не поддерживается показывается пустой тулбар инструментов. Когда все кнопки для этих типов будут реализованы - все будет работать штатно.

**Comment by BishopGIS** [comment]
Я подправил. Теперь при клике на карандаш будет сообщение, что данный тип слоя не поддерживается. В диалоге выбора слои которые не поддерживаются, тоже не показываются.

**Comment by simgislab** [comment]
Удаление тоже должно вызывать такое сообщение.

Сейчас при удалении мне говорят, что фича удалена, но ничего на самом деле не удаляется.

**Comment by BishopGIS** [comment]
Ну по идее не должно сообщени выводится. Проблема редактирования только в том, что не все кнопки панели инструментов для редактирования и создания мултилиний и мультиполигонов реализованы. Удаление тут не причем и может вполне спокойно на таком слое выполняться (так же как и запрос атрибутов и другие операции). Само удаление было несколько поломано (экран не обновлялся) - починил вроде.
