### ISSUE TITLE
На слоях из NGW при нажатии на Поделиться ничего не происходит

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#236]

**Comment by simgislab** [comment]
на каком слое? векторные у меня "делятся" нормально

**Comment by drnextgis** [comment]
На векторном и PostGIS слоях из ngw.
01.10.2015 19:40 пользователь "Maxim Dubinin" <notifications@github.com>
написал:

**Comment by simgislab** [comment]
суть в слоях NGW, на обычных все ок
