### ISSUE TITLE
Proceed -> Process

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#240]
>< string name="proceed_features" >Proceed features</string>
>< string name="proceed" >Proceed</string>

Process features
Process

>< string name="proceed_layer" >Proceed layer</string>
Process layer

Сам не поправил, потому что я бы поменял и значение в name на process*. Сейчас это явно ошибка.

**Comment by BishopGIS** [comment]
Fix in 7d1a1e45d02d4026a8824769435d0fd38beeb526
