### ISSUE TITLE
Пропадают объекты при редактировании слоя PostGIS

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#241]
Загружаем слой PostGIS любой, например http://demo.nextgis.ru/ngw/resource/74, лонг тап на любой геометрии, появляется панель снизу, тапаем на другую геометрию - она пропадает. Если не получается воспроизвести - попробовать пару раз на других объектах, довольно легко воспроизводится.

**Comment by simgislab** [comment]
Стабильно воспроизводится, просто долгий тап и карандаш - фича исчезает

![](http://m-d.me/img/ss/20151002-y84-111kb.jpg)
