### ISSUE TITLE
При шаринге слоя добавлять фото

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#243]
При выполнении операции "поделится" экспортировать не только геометрии и атрибутику, но и вложения в виде архива.

**Comment by 4eRTuk** [comment]
Структуру оставить такую же, какая сейчас используется для хранения фото в приложении? Нужно ли добавлять ссылки на фото в каждую фичу в выходной geojson?

**Comment by simgislab** [comment]
Добавить ссылки в выходной geojson было бы очень круто.

**Comment by BishopGIS** [comment]
Да. Структуру надо сохранять. А вот как писать ссылку в json не понятно - там же может несколько фоток к одной фиче. Как это сделать?

**Comment by 4eRTuk** [comment]
Думаю массивом просто. Что-то типа "photos: [path1, path2, path3]"

**Comment by BishopGIS** [comment]
Боюсь от такого вида  QGIS будет не в восторге.

**Comment by simgislab** [comment]
Re: [android_gisapp] При шаринге слоя добавлять фото (#243)


а можно просто чкрез точку с запятой писать?

Вы писали 14 октября 2015 г., 22:02:26:





Боюсь от такого вида QGIS будет не в восторге.

**Comment by BishopGIS** [comment]
Можно, но ты понимаешь что это будет выглядеть так: 1, 2, 3
Т.к. у нас фотки нумеруются просто цифами.

**Comment by simgislab** [comment]
Re: [android_gisapp] При шаринге слоя добавлять фото (#243)


ну что поделаешь, значит так и будет, только наверное 1.jpg,2.jpg и т.д.

нормально для начала

Вы писали 14 октября 2015 г., 22:55:07:





Можно, но ты понимаешь что это будет выглядеть так: 1, 2, 3
Т.к. у нас фотки нумеруются просто цифами.

**Comment by BishopGIS** [comment]
Они у нас вроде без расширений хранятся:
https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/map/VectorLayer.java#L976
Правда отдельно хранится имя (этот все из-за НГВ - там такая модель для вложений).
И по хорошему аттачи надо переименовывать при вложении в архив согласно имени - https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/map/VectorLayer.java#L982.

**Comment by 4eRTuk** [comment]
Имена могут быть и одинаковыми. Еще как возможный вариант - сохранять изображение прямо в geojson в виде base64.
