### ISSUE TITLE
Добавить в about ссылки

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#245]
1. Ссылку на страницу приложения
2. Ссылку на документацию
3. Ссылку на баги

**Comment by simgislab** [comment]
ссылки хватит одной, а вот текст по ссылке уже должен все хорошо описывать

**Comment by 4eRTuk** [comment]
Какую ссылку добавлять? Еще предлагаю перенести Credits в диалоговое окно по кнопке, а то много места занимает.

**Comment by simgislab** [comment]
давай оставим только nextgis.com
все остальное уберем в Credits да

**Comment by 4eRTuk** [comment]
У нас есть уже на nextgis.com ссылка в копирайте. Может на гитхаб?

**Comment by simgislab** [comment]
Давай так:
 - копирайт остается
 - под текстом добавляется кнопка или ссылка Contact us со ссылкой на http://nextgis.ru/en/contact/
Ну и кредитс.
