### ISSUE TITLE
Не убираются контролы ZoomIn и ZoomOut

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#25]
При их отключении через меню они отключаются, но сами кнопки с экрана не исчезают.

**Comment by BishopGIS** [comment]
У меня не воспроизвелось

**Comment by simgislab** [comment]
подтверждаю

**Comment by drnextgis** [comment]
Обновился, баг не исчез.

**Comment by simgislab** [comment]
аналогично

**Comment by simgislab** [comment]
у меня снова не отключаются через настройки

**Comment by drnextgis** [comment]
Подтверждаю, у меня аналогично.
