### ISSUE TITLE
Improve processing on import indicator

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#254]
I'd show percentages and number of features for vector layer.

I'd show percentages and number of tiles (better) or Mb (worse) for raster layer.

The line after title should go away.

Currently numbers are very confusing.

![](http://nextgis.ru/wp-content/uploads/2015/10/Screenshot_2015-10-06-12-21-21-576x1024.png)

**Comment by BishopGIS** [comment]
In some cases this information is thery usefull. For example the loading of
a layer interapted by timeout or any other problems. Also you can control
the speed of feature processing and feature count. The json stream size is
less informative than feature count.

**Comment by simgislab** [comment]
this is debug for dev, not for users

**Comment by BishopGIS** [comment]
Actually not. This is typical user case, not debug. User think features not bytes. 
For example there are 10 polygon feature. First 5 features have only 4 point, and other 5 - 100 000 points. User will wonder why loading stops on 50%. But in case of feature count it'll be clear that smartphone process so big geometry.

**Comment by 4eRTuk** [comment]
What is in sum? How should we process that?

**Comment by BishopGIS** [comment]
I vote to not change this dialog now. May be in case of milestones/3.0 the processes will look something else.

**Comment by simgislab** [comment]
this case wait till 2.4-3.0

**Comment by 4eRTuk** [comment]
Now only percentage and custom message are shown.
