### ISSUE TITLE
При загрузке слоя поворот экрана закрывается диалог процесса загрузки

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#259]
Диалог закрывается при повороте экрана, а должен закрываться только по завершению операции или при нажатии кнопок на нем. 
Алтернативно можно добавить в статус баре вторую кнопку - показать диалог.

**Comment by simgislab** [comment]
Диалог чего?

**Comment by BishopGIS** [comment]
Диалог с прогрессом загрузки закрывается. Исправил название.
