### ISSUE TITLE
Изменяется цвет шрифта

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#26]
Это так и задумано? Сначала запустил - цвет черный, потом становится серым.
![screenshot_2015-02-04-09-08-19](https://cloud.githubusercontent.com/assets/866124/6034538/7b9f89f6-ac45-11e4-9531-6829e1b3d42d.png)
![screenshot_2015-02-04-09-09-25](https://cloud.githubusercontent.com/assets/866124/6034539/7bb22c8c-ac45-11e4-8ff7-be5ce4bbc9fb.png)

**Comment by BishopGIS** [comment]
Интересный глюк. Похоже на туже историю со стилями

**Comment by BishopGIS** [comment]
Чего-то у меня не воспроизводится. Потом становится серым, это после каких действий?

**Comment by drnextgis** [comment]
Похоже что так: после какого-нибудь крэша приложения - шрифт чёрный, в последующие запуски серый.

**Comment by 4eRTuk** [comment]
Я тоже не могу поймать. @drnextgis у тебя еще воспроизводится?

**Comment by simgislab** [comment]
@drnextgis у тебя еще воспроизводится?
