### ISSUE TITLE
Подставлять текущую дату и время в соответствующий контрол

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#263]
Отсюда https://github.com/nextgis/formbuilder/issues/64

**Comment by 4eRTuk** [comment]
Тогда наверное стоит убрать поле для дефолтного значения из FB? А то неразбериха получается.

**Comment by BishopGIS** [comment]
Почему? Если нет дефолтного значения - NULL в json - тогда текущую дату выводить.
