### ISSUE TITLE
Не открывается на Nexus 5

### ISSUE THREAD

**Issue by miminovich** [nextgis/android_gisapp#266]
При попытке открытия на Nexus 5 "Unfortunately, NexGIS Mobile has stopped".
Android 6.0, security patch level November 1, 2015

**Comment by BishopGIS** [comment]
Мы проверяли на 6-ке. Версия из маркета может не работать если не даны права на GPS и камеру. В 6-й версии права настраиваются отдельно - http://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/
Сейчас подправили, будет блокироваться только фукнционал на который не даны права, но релиза в маркете еще не было.

**Comment by miminovich** [comment]
Благодарю. Вручную дал права - приложение запустилось.

ср, 18 нояб. 2015 г. в 10:55, Dmitry Baryshnikov <notifications@github.com>:

> Мы проверяли на 6-ке. Версия из маркета может не работать если не даны
> права на GPS и камеру. В 6-й версии права настраиваются отдельно -
> http://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/
> Сейчас подправили, будет блокироваться только фукнционал на который не
> даны права, но релиза в маркете еще не было.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/android_gisapp/issues/266#issuecomment-157648052>
> .
>
-- 
---
Center for Regional Studies
65074, Ukraine, Odessa, Gaidar Str. 3-a
Tel/fax: +380 48 7198536
E-mail: sizo.roman@gmail.com, utsc@te.net.ua
Web: www.crs.org.ua

**Comment by BishopGIS** [comment]
Fixed in https://github.com/nextgis/android_gisapp/commit/3fed9386cb211028f16a079faed145105c387e3e
