### ISSUE TITLE
Кривой компас

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#267]
Запускаю приложение, сворачиваю, восстанавливаю через некоторое время. Компас становится кривым. 
![screenshot_2015-11-17-15-32-46](https://cloud.githubusercontent.com/assets/866124/11238037/ef7071fa-8e04-11e5-9780-15e2ece12b8b.png)

**Comment by NikitaFeodonit** [comment]
Если свернуть и сразу вернуться, то вид нормальный?

**Comment by drnextgis** [comment]
Нет, ничего не меняется.

**Comment by NikitaFeodonit** [comment]
Проверил у себя. Если сразу после запуска приложения свернуть его и вернуться к нему сразу же, то всё хорошо. Если же процесс приложения был снят системой по нехватке памяти, то появляется эта проблема.

Как отлаживать и что делать в таких случаях, очень хорошо описано тут:
http://habrahabr.ru/post/261721/

**Comment by simgislab** [comment]
да, у меня тоже самое
