### ISSUE TITLE
Не определяется тип локального слоя

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#27]
Вместо этого пишет `Not available`.
![screenshot_2015-02-04-09-13-58](https://cloud.githubusercontent.com/assets/866124/6034570/e8e48516-ac45-11e4-9de1-97e7cd650551.png)

**Comment by BishopGIS** [comment]
Fix in 14d7d6d793f1ac50fe92514606af3d3e64b66f91
