### ISSUE TITLE
Счетчик "Обработано N из M" врет при загрузке архива тайлов

### ISSUE THREAD

**Issue by alisovenko** [nextgis/android_gisapp#272]
Загружал архив на 20 мб, созданный в QTiles
При загрузке в сообщении "Обработано N из M"
N всегда уходил далеко за M

По достижении M==N интерфейс пишет - выполнено 100%, но N продолжает увеличиваться.
В итоге N достигает значения примерно 2M. Слой загружается успешно.

**Comment by alisovenko** [comment]
NGM v. 2.2.2 (rev. 12)

**Comment by 4eRTuk** [comment]
Будет исправлено в #254

**Comment by simgislab** [comment]
Стас, поясни плиз, т.е. оно в 2.3 релизе не будет исправлено?

**Comment by 4eRTuk** [comment]
Мы же на 2.4 перенесли.

**Comment by simgislab** [comment]
да, но в #254 мы обсуждали более существенную переделку, а здесь, как я понял, речь идет о какой-то банальной ошибке, или нет?
