### ISSUE TITLE
Сделать возможность изменить геометрию через обход

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#283]
Для линий, мультилиний, полигонов и мультиполигонов иметь возможность дополнить сегмент заданный пользователем обходом.

**Comment by 4eRTuk** [comment]
Я предлагаю изменить добавление через обход - при добавлении новой геометрии или при редактировании существующей запускать режим редактирования, но делать неактивными все остальные кнопки. Так мы избавимся от одного довольно бесполезного тулбара и приведем к общему виду всё редактирование. Но в этом случае не предусматривается редактирование других геометрий (см. #284).

**Comment by simgislab** [comment]
ты можешь по шагам расписать, я потерялся в описании #283 и #284

**Comment by 4eRTuk** [comment]
1. панель с крестиком, дискетой и настройками (обход) убирается
2. открывается режим редактирования и активируется дискета
3. редактирование геометрий запрещено

**Comment by BishopGIS** [comment]
Мне кажется предложение @4eRTuk логичным. Я поддерживаю.

**Comment by 4eRTuk** [comment]
Duplicate #102
