### ISSUE TITLE
Реализовать работу кнопки добаления геометрии при обходе

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#284]
При вводе геометрии обходом имеется кнопка для добавления новой геометрии. При нажатии на кнопку необходимо:
1. Показать диалог выбора слоя для добавления/изменения геометрии.
2. Создать второй оверлей для редактирования и запустить в нем редактирование геометрии.
3. После завершения редактирования вернуться в режим ввода обходом.

Я так понимаю второй оверлей должен быть расширением класса EditLayerOverlay, но с переопределенными методами завершения редактирования (что бы не возвращаться в обычный режим MODE_NONE, а в режим MODE_EDIT_BY_WALK).

**Comment by 4eRTuk** [comment]
Мне кажется слишком сложно для мобильного устройства. Будет 4 панели в худшем случае.

Может имеет смысл убрать из нижней панели сохранение/отмену обходом в отдельные кнопки или еще как-нибудь видоизменить процесс добавление геометрии обходом?

**Comment by BishopGIS** [comment]
Я предлагал при переходе к редактированию слоя из редактирования линии обходом менять панели. Т.е. их количество не должно увеличиться, а изменится интерфейс на редактирование соответствующего слоя. При выходе из интерфейса редактирования слоя, должен вернуться интерфейс редактирования линии/полигона обходом.

Панели не должны плодиться. Вообще это должно быть похожим на то как сейчас меняется интерфейс при переходах:
обычная карта -> выбор действия (идентификация, удаление и.т.п.)
выбор действия -> редактирование

а тут должно быть
редактирование обходом -> редактирование
