### ISSUE TITLE
Нелогичное меню работы со слоями

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#287]
Ранее иконка которая назначена на создание слоя - обозначала добавление слоя.
Теперь она же обозначает создание слоя. Это сбивает с толку тех кто уже пользуется программой.
Предлагаю перенести создание нового слоя как отдельный пункт (пусть будет первым) в подменю "Открыть слой". Соответственно меню переименовываем в "Слой".
И подменю будет вот таким:

* Создать новый
* Открыть локальный
* Открыть веб
* Открыть НГВ

**Comment by simgislab** [comment]
а с кнопкой тогда как?

**Comment by BishopGIS** [comment]
А у нас была же кнопка (просто теперь их 2 одинаковых). Так и останется одна по которой меню открывается.

**Comment by 4eRTuk** [comment]
Макс наверное про кнопку в боковом меню. Её оставляем?

**Comment by BishopGIS** [comment]
Да, ее оставляем.
