### ISSUE TITLE
Добавить возможность отключения ввода атрибутов

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#289]
Для того, чтобы после каждого ввода геометрии не выскакивало окно с атрибутами.

**Comment by BishopGIS** [comment]
Мне кажется это не правильно. Это ГИС и ввод атрибутов как часть геоданных
- обязателен.

**Comment by drnextgis** [comment]
Да, но это эти операции же не обязательно выполнять одновременно, атрибутику можно заполнить позже.

**Comment by BishopGIS** [comment]
Да, только не заполнить, а изменить. Это все таки не настольная ГИС, что бы
тут такие сложные сценарии реализовывать. Это как редактирование геометрией
в вебе - можно, но сложно.

**Comment by simgislab** [comment]
мне кажется это была бы хорошая фича, многие хотят "просто точек понаставить"

**Comment by BishopGIS** [comment]
Для таких кто хочет просто точек, есть Автокад. Мы побуждаем пользователей производить геоданные - атрибутика обязательна (если конечно слой создан с атрибутами).

**Comment by simgislab** [comment]
причем тут автокад...отсутствие атрибутики не означает что это не геоданные. Еще раз, задача "натыкать точек" весьма распространена и никто не мешает ввести атрибуты позже.

Первый "мой" коммит в кугис был такой же - отключение назойливой панели ввода атрибутов появляющейся сразу после создания объекта. До этого они тоже всех заставляли "производить геоданные".

Не надо это делать пока, но в будущих релизах к этому нужно будет вернуться.

**Comment by BishopGIS** [comment]
Почитайте определение геоданных.
А просто точек натыкать есть яндекс карты - там это очень удобно делать, но зачем?
Если следовать логике - "понатыкать", надо ВСЕ менять. Убирать слои и другие ГИС штуки.
Один слой и тыкай чего хочешь - и двигаемся обратно к OSMDroid.
Я не против QGIS, в десктопе это правда просто, но в мобильном - вы делаете очень странные и сложные в исполнении предложения. Давай в вебе тогда сделаем редактирование с топологией - это гораздо чаше спрашивают причем на тот же яндекс редактор народных карт показывают.

**Comment by drnextgis** [comment]
Не очень понял в чём сложность, ведь мы сейчас при создании объекта получаем окно ввода атрибутики, но можем его не заполнять, а просто нажать галку. Если бы была возможность отключать ввод атрибутики, то это просто происходило бы автоматом.

**Comment by BishopGIS** [comment]
Логика создания записи окончательной записи как раз и реализована в окне ввода атрибутов. А иначе эту логику надо тащить в оверлей, где редактирование. А он и так уже супер сложный получился в результате чего падения. Я уже думаю как бы его упростить и разгрузить.
