### ISSUE TITLE
Удаляется геометрия при редактировании

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#290]
Не понятно что происходит. Полигональный слой. При выделенном полигоне нажимаем Добавить полигон. Выделенный полигон исчезает с карты. Предположим, что новая геометрия заменяет старую, но почему тогда в настройках слоя счетчик объектов увеличивается на 1

**Comment by simgislab** [comment]
>При выделенном полигоне нажимаем Добавить полигон
Я как не мучался, так и не понял как это сделать. Полигон нарисовал, выделил, но в панели внизу у меня только добавить точку.

**Comment by 4eRTuk** [comment]
Сделал замену геометрии на новую, сейчас должно корректно работать. Предлагаю подумать про переделку нижней панели - может стоит заменять верхнюю на действия создания, удаления, редактирования атрибутов объекта слоя, а в нижней оставить действия с точками и мультигеометриями.

**Comment by drnextgis** [comment]
Проверил на последней сборке - ничего не поменялось, создания полигона при выделенном добавляет +1 к количеству объектов в слое.
