### ISSUE TITLE
Добавление слоя из ngw приводи к крэшу

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#294]
Вот этот слой http://demo.nextgis.ru/ngw/resource/198. Возможно, из-за невалидного имени поля.

**Comment by simgislab** [comment]
подверждаю

**Comment by drnextgis** [comment]
Больше не крэшится, но вот такое сообщение:

![screenshot_2015-12-27-12-43-40](https://cloud.githubusercontent.com/assets/866124/12015656/6d78bf64-ad61-11e5-83e2-a6c7318d604b.png)

**Comment by BishopGIS** [comment]
В имени поля Ob'ekt надо фильтровать одинарную кавычку. 
https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/util/LayerUtil.java#L51
