### ISSUE TITLE
Геометрия сбрасывается к первоначальной

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#296]
При редактировании существующего полигона если сменить ориентацию экрана (повернуть телефон), то геометрия сбрасывается к первоначальной.

**Comment by simgislab** [comment]
Да, подтверждаю, причем с новым полигоном не воспроизводится (точнее с этим непонятно, один раз кажется словил, но потом крутил вертел новый измененный треугольник и ничего к первоначальному не сбрасывается).

А вот с редактированием существующего да - сбрасывается стабильно.
