### ISSUE TITLE
Сделать возможность звукового сигнала при завершении снятия усреднённых координат

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#30]
Пригодится для работы в таком режиме
![oi000008](https://cloud.githubusercontent.com/assets/4630662/6287804/67ed3c4a-b925-11e4-86c4-50e6979646af.jpg)

**Comment by 4eRTuk** [comment]
Fix in 1a7a8137bf6193c4829d51b550a5e70f932bdea2
