### ISSUE TITLE
Полосы между тайлами Спутника

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#300]
При добавлении подложки Спутник http://tiles.maps.sputnik.ru/{z}/{x}/{y}.png - на последнем масштабном уровне видны полосы между тайлами. Возможно, это как-то связано с тем, что у Спутника тайлы 512x512.

**Comment by simgislab** [comment]
подтверждаю, но больше меня волнуют не полосы, а то что половина тайлов не подгружается, а если обновить, то часть появится, а часть снова нет

**Comment by BishopGIS** [comment]
У нас поддерживаются тайлы только 256 х 256. Так что не удивительно сто не
работает.

**Comment by BishopGIS** [comment]
Fix in https://github.com/nextgis/nextgis_datastore/ will be available in NGM3
