### ISSUE TITLE
Кнопка синхронизации

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#301]
Если синхронизация отключена, то должна ли присутствовать в дереве слоёв кнопка со стрелками (синхронизация)?

**Comment by BishopGIS** [comment]
Текста "последняя синхронизация..." быть не должно, кнопка - должна.
Крайняя установка была такой.

**Comment by simgislab** [comment]
не нужно показывать надпись и кнопку в дроувере если нет ни одного слоя

**Comment by simgislab** [comment]
see #288
