### ISSUE TITLE
Пропадают объекты из слоя

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#303]
1. Подключаем NGW (http://178.62.222.113:6543, administrator/gisconf2015)
2. Добавляем слой: Уборка внутридворовых территорий - Зоны ответственности (вектор)
3. Смотрим в настройках слой - количество записей 2
4. Долгий тап на полигоне (я делал на правом) - Карандаш - Редактировать атрибуты - Добавляем фотографию - Сохраняем
5. Открываем настройки слоя - теперь количество записей - 1

**Comment by simgislab** [comment]
я дохожу до шага 4, потом после сохранения он мне говорит "Слой не инициализирован" и больше редактировать мне его не дает. 

Панель внизу становится простой голубой полоской, без инструментов и больше не убирается никак.

**Comment by BishopGIS** [comment]
Воспроизводится точно как описал @drnextgis
