### ISSUE TITLE
Игнорируется настройка только GPS при рисовании обходом

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#310]
Даже если стоит, все равно точки отскакивают, проверено на линиях и полигонах

**Comment by 4eRTuk** [comment]
Сейчас настройка берется из секции "Треки". В ней какая настройка для источников задана?

**Comment by BishopGIS** [comment]
Вообще помнится настройка должна браться из секции местоположение. Это сделано потому что трек - это все такие вещь стандартная, а ввод полигона - тут есть выбор. И кстати, тогда все правильно что есть выбросы - т.к. сотовые вышки и вафля тянет на себя.

**Comment by simgislab** [comment]
треках у меня стоит GPS

**Comment by BishopGIS** [comment]
Поставьте везде только GPS и в треках и в местоположении.

**Comment by simgislab** [comment]
#200
