### ISSUE TITLE
Индикация записи трека

### ISSUE THREAD

**Issue by KoGor** [nextgis/android_gisapp#312]
Сейчас, когда включаешь запись трека, обратная реакция со стороны приложения минимальна. С первого раза текущий notification вряд ли можно заметить. А если выйти на время из приложения,  и зайти позже, то о включённом треккинге вообще никакого намёка. А при выключении треккинга даже notification не всплывает. Предлагаю отражать включённую запись в виде изменённого состояния иконки, например, делать человечка красным во время записи.

**Comment by PavelDuk** [comment]
KoGor, здравствуйте) Как с вами можно связаться? Дело в том что мы делаем сервис, но ваша карта России у нас криво встает. Просим вашей помощи! blazing.moment@yandex.ru

**Comment by simgislab** [comment]
вы о чем?
