### ISSUE TITLE
Can't edit a donut polygon

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#314]
I can create a donut shaped polygon.

But after saving, I can't reselect it to modify. Polygon works fine in QGIS.

https://www.dropbox.com/s/2dedqf6h1d00871/%D0%9F%D0%BE%D0%BB%D0%B8%D0%B3%D0%BE%D0%BD%D1%8B.zip?dl=0

**Comment by 4eRTuk** [comment]
It's not shape related problem. RTree geometry cache again - some features not selecting or missing.

**Comment by BishopGIS** [comment]
У меня не воспроизводится. Есть только баг с созданием geojson - там srs в конце и при загрузке координаты считаются градусами, а на самом деле - это метры

**Comment by BishopGIS** [comment]
Исправленный geojson во вложении.
[Полигоны.zip](https://github.com/nextgis/android_gisapp/files/87068/default.zip)

**Comment by simgislab** [comment]
я загрузил исправленный - у меня он все равно не выделяется никак и не редактируется

**Comment by BishopGIS** [comment]
Исправленный файл - он не для тебя. В твоем устройстве слои идентичны. И ошибка будет повторятся.
Вот только непонятно - это твой персональный баг или все таки у кого-то еще воспроизводится?

**Comment by simgislab** [comment]
@drnextgis можешь проверить? Потыкай в стадион в районе мэдисона) на остальные полигоны внимания не обращай

**Comment by Kinda-me** [comment]
У меня стадион отредактировался.

![screenshot_2016-01-12-21-57-05](https://cloud.githubusercontent.com/assets/6493848/12273543/820465e2-b977-11e5-83ce-32a69446506d.png)

**Comment by 4eRTuk** [comment]
@simgislab попробуй перестроить кэш в настройках слоя.

**Comment by simgislab** [comment]
помогло!
