### ISSUE TITLE
zipped vector layers

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#318]
Right now zips are treated as sources of tiles, so packed geojson won't load

Can we use some logic to determine if this is vector data inside and load correctly

**Comment by 4eRTuk** [comment]
Yes, we can. But do we need this? Just upack geojson from zip and import it.

**Comment by simgislab** [comment]
less file operations is better

reading zipped layers is possible in NGW and QGIS, people got used to it
