### ISSUE TITLE
Помечать красным цветом контролы без сопоставленных полей

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#319]
Форма из nextgis/docs_ngmobile#5 не позволяет менять:
1. текст в текстовом поле
2. выбор списка
3. выбор из связного списка
4. чекбокс
5. выбор даты и времени

Работают только радиокнопки и выбор/съемка фото, подписи.

**Comment by simgislab** [comment]
да, подтверждаю, может это потому что я этой форме не назначил полей связанных? там просто контролы

**Comment by BishopGIS** [comment]
А какое поведение должно быть в таком случае? А то в тупик ставит. 
Не отображать не вариант. Было бы неплохо красным как-то выделять.

**Comment by 4eRTuk** [comment]
Да, значения контролов без полей не меняются

**Comment by simgislab** [comment]
Да, еще лучше делать серым, типа заблокировано.

Сделал еще форму с подключенными полями:
https://www.dropbox.com/s/ei7ncei2dz1qa3h/form-all-controls-f.ngfp?dl=0
