### ISSUE TITLE
Autopan map while moving

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#32]
Currently the map is not being recentered while tracking. Common practice is different:

1. After tracking started - the map should be recentered automatically. I.e. tracking symbol should always in the center
2. If the map is paned somewhere by the user, the automatic recentering is stopped.
3. If locate button is used - automatic recentering continues.

**Comment by BishopGIS** [comment]
I think this feature not connected with tracking and should be done like in
yandex.map: autopan if current location is visible.

**Comment by BishopGIS** [comment]
Хочу в 2.2 а то на машине невозможно пользоваться.

**Comment by BishopGIS** [comment]
Текущая реализация зацикливает отрисовку, в результате ничего не отображется.
Сейчас вызов panTo размещен в методе draw CurrentLocationOverlay в результате вызова отрисовки происходит вызов panTo который в свою очередь вызывает отрисовку и так по кругу. 
Нужно вызова panTo повесить на изменени координат LocationListener. При этом если даже вызов произошел, но координаты не сильно отличаются (~1-2 м)  не вызывать panTo.
Проблемное место: https://github.com/nextgis/android_maplibui/blob/vector-tiles/src/main/java/com/nextgis/maplibui/overlay/CurrentLocationOverlay.java#L170-170
А вот сюда видимо надо вставить: https://github.com/nextgis/android_maplibui/blob/vector-tiles/src/main/java/com/nextgis/maplibui/overlay/CurrentLocationOverlay.java#L286

**Comment by BishopGIS** [comment]
У меня работает - закрываю.
