### ISSUE TITLE
Падение сразу после установки

### ISSUE THREAD

**Issue by dbf256** [nextgis/android_gisapp#320]
http://clip2net.com/s/3sYVTpj
Nexus 5/Android 6.0.1. Если можно как-то достать дополнительные логи, то сообщите и я прицеплю.

**Comment by BishopGIS** [comment]
А версия какая? Из маркета или от сюда: https://tsfr.io/804gdm
?

**Comment by dbf256** [comment]
Из маркета (2.2.1)

**Comment by BishopGIS** [comment]
У вас прав на GPS не дано. В новой версии (ссылку на тестирования я дал) падение исправили, но правва все таки стоит дать - а то останетесь без GPS.
Про права подробнее например тут: http://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/

**Comment by BishopGIS** [comment]
Дублирует #266. Закрываю.

**Comment by dbf256** [comment]
Да, теперь заработало. Спасибо!
