### ISSUE TITLE
Accuracy indicator

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#327]
The app should allow to both visualize graphically on the map as well as on a string the accuracy:
- Using the mockup location we also override the accuracy value (e.g. 0.1 meters accuracy)
- On screen normally is shown as a circle on top of the position which is handy to immediately visualize the accuracy
- Note that some GNSS receivers output accuracy in 2DRMS while Android expects it in DRMS (in our app we added an option though)

**Comment by 4eRTuk** [comment]
Accuracy circle was not shown on small zooms, now it's shown.

How should we process 2DRMS receivers? Android LocationManager return fixes in DRMS only.
