### ISSUE TITLE
Ошибка работы на Android 2.2

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#33]
1. Карта не панится
2. Кнопка FAB не синяя
3. Тайлы не рисуются

![device-2015-03-04-235305](https://cloud.githubusercontent.com/assets/1708122/6493149/d63dd8dc-c2c9-11e4-9317-b358d0ad84b1.png)

**Comment by NikitaFeodonit** [comment]
... NGW-подключение не создается.

)

**Comment by BishopGIS** [comment]
Создается. Я проверил. Последний транк поставь.
