### ISSUE TITLE
В приложении NextGIS Mobile при добавлении слоя GeoJSON или формы приложение прекращает роботу

### ISSUE THREAD

**Issue by bagration26** [nextgis/android_gisapp#339]

**Comment by simgislab** [comment]
- сообщите версию NextGIS Mobile
- приложите слой или фрагмент слоя на котором приложение прекращает работу
- приложите файл ngfp (форма) на котором приложение прекращает работу

**Comment by 4eRTuk** [comment]
Возможно из-за этого https://github.com/nextgis/android_gisapp/issues/415

**Comment by simgislab** [comment]
обратной связи нет, закрываю
