### ISSUE TITLE
Управление отображением панели информации

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#34]
Существует 2 подхода:
1. Кнопка в тулбаре для включения/отключения панели (так было в NextGIS Mobile v1)
2. Вынести включение панели в настройки приложения

Вопрос всем, как лучше сделать?

Панелька определяет можно ли выводить информацию в одну строку или в две. См. скриншоты. На цвети и прозрачность пока не смотрим - это еще в процессе. Должно быть как у тулбара. А прозрачность тулбара в настройках приложения. 

![screenshot_2015-03-07-16-47-00](https://cloud.githubusercontent.com/assets/1708122/6541553/20648d44-c4ea-11e4-9034-60eac3e25019.png)

![screenshot_2015-03-07-16-48-40](https://cloud.githubusercontent.com/assets/1708122/6541554/24c79a02-c4ea-11e4-85bc-246bc554fc73.png)

**Comment by simgislab** [comment]
имхо, в настройки
место для кнопок в тулбаре явно еще понадобится

**Comment by yellow-sky** [comment]
с настройки, но на верхний уровень, чтобы можно было включить одним тачем.
2 строки - плохо! нужно уместить все в одну.

**Comment by drnextgis** [comment]
Не очень понятна необходимость функций настройки вывода в одну строку или в две, а почему не три и т.д. Может сделать настраиваемым список отображаемых показателей и компоновать их автоматом в столько строк, во сколько они войдут в зависимости их числа и выбранного размера шрифта. А по сабжу, да, мне кажется лучше в настройки.

**Comment by BishopGIS** [comment]
Что не вмещается в тулбар переносится автоматом в меню (3 вертикальных точки). Там уже есть пункт запись треков. Я посмотрел порядок определения количества кнопок в тулбаре. См. табличку (от 2-х до 5 кнопок, не более): 
http://developer.android.com/design/patterns/actionbar.html#ActionButtons

**Comment by BishopGIS** [comment]
@drnextgis панель много места занимает. Надо было что бы карту не забивало. Предложенный тобой вариант можно сделать на перспективу (заводи тикет).

**Comment by BishopGIS** [comment]
@yellow-sky - на верхний уровень не получится (если только на планшете). Тут как раз если быстро включать - надо в тулбар, если нет - то в настройки.

**Comment by drnextgis** [comment]
@BishopGIS, а можно сделать какой-то небольшой маркер, например в середине нижней части экрана, который можно тапать для показа/сокрытия панели?

**Comment by BishopGIS** [comment]
@drnextgis  Это нарушает дизайн - положено только одну основную кнопку выносить - так и вынесли в виде большой круглой кнопки (FAB). Все остальное либо в настройки, либо в тулбар (меню). Есть вариант добавить кнопку закрытия панельки (так сейчас сделано с панелями выбора действия и редактирования).

**Comment by BishopGIS** [comment]
Вот как выглядят панельки у яндекса:
![screenshot_2015-03-07-17-31-35](https://cloud.githubusercontent.com/assets/1708122/6541691/28c6dd38-c4f0-11e4-87f4-357380b9778c.png)

![screenshot_2015-03-07-17-31-49](https://cloud.githubusercontent.com/assets/1708122/6541693/2d9fcd7e-c4f0-11e4-9850-1533cff313b7.png)

**Comment by BishopGIS** [comment]
По итогам голосования оставляем как есть - в настройках.
