### ISSUE TITLE
Labeling field

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#341]
Add ability to select a Labeling field in layer properties.

Use value from this field for a record to show instead of Object #1 and in future for labeling.

**Comment by simgislab** [comment]
тоже не увидел это в интерфейсе

**Comment by 4eRTuk** [comment]
Задается в "Настройки слоя -> Поля -> Кликнуть по полю"

**Comment by simgislab** [comment]
уф, трудно догадаться, сообщение не особо видно, может прямо в заголовок добавить:
```Fields (tap to select as default)```

**Comment by 4eRTuk** [comment]
Оно же всплывает :)
Можно и в заголовок конечно.

**Comment by simgislab** [comment]
его совершенно не видно глазом, если оно всплывает вместе с окном

**Comment by simgislab** [comment]
еще, похоже что есть в полях ID и TEXT пусто, но выбрать одно из них как Label, то приложение валится
