### ISSUE TITLE
Очистка слоя при синхронизации

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#359]
Необходимо проверить ситуацию. Есть слой, который доступен только для чтения и синхронизируется с устройством. Есть репорт, что слой при операции синхронизации очищается.
Нормальное поведение - слой обновляется данными с сервера.
Возможно слой пытаются редактировать. Такие записи не должны перекрываться с сервера.

**Comment by BishopGIS** [comment]
Возможно связано с nextgis/nextgisweb_forest_violations#22

**Comment by 4eRTuk** [comment]
Все работает. Из-за мультигеометрий и правда слой очищался, сейчас исправлено.
