### ISSUE TITLE
Медленная идентификация - при добавлении точечного слоя не строится индекс

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#368]
Использую NextGIS Mobile для просмотра данных жилого фонда СПб: слой в 25 тысяч точек.
Идентификация занимает около 40 секунд: сначала приложение виснет, потом ОС предлагает его закрыть, потом появляется окно идентификации. 
Возможно не строится индекс. Попробовал запустить индексацию вручную, но быстрее как-то не стало.

**Comment by trolleway** [comment]
[Пример данных.geojson.zip](https://github.com/nextgis/android_gisapp/files/191525/housedata_spb_crop.zip)

**Comment by 4eRTuk** [comment]
Что значит идентификация?

**Comment by BishopGIS** [comment]
Когда долгим тапом выбираешь точку или при показе атрибутов. В любом случае 40 секунд - это много.
