### ISSUE TITLE
Проверять версию НГВ

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#370]
АПИ: http://demo.nextgis.ru/ngw/api/component/pyramid/pkg_version

Сейчас имеется 2 версии НГВ в которых по разному организована работа с веторными слоями (2.х и 3.х)

В версии 2.х и ниже (или нет версии совсем) все геометрии векторного слоя приводятся к типу мульти (это не касается PostGIS слоя).
В версии 3.0 и выше тип геометрии точно соответствует.

Алгоритм такой - при создании слоя из НГВ, если версия НГВ 2.х или неизвестно, то для векторного слоя тип геометрии приводится к мульти (старое поведение).
При создании слоя из НГВ 3.0 >= тип геометрии устанавливается как есть (без преобразований).

**Comment by NikitaFeodonit** [comment]
Сервер demo сейчас отдает два поля:
{
	"nextgisweb": "2.0",
	"nextgisweb_mapserver": "0.0dev"
}

По "nextgisweb" выше описано понятно. Но как реагировать на поле "nextgisweb_mapserver"?

**Comment by BishopGIS** [comment]
Игнорировать. Для мобильного неактуально.

**Comment by BishopGIS** [comment]
@NikitaFeodonit все работает -  закрываем?

**Comment by NikitaFeodonit** [comment]
Если всё работает, то закройте.
