### ISSUE TITLE
разный формат координат в настройках и во всплывающих окнах

### ISSUE THREAD

**Issue by ABiatov** [nextgis/android_gisapp#374]
В настройках NGM указан формат координат GG.GGGGG
Но при просмотре атрибутивной информации созданных точечных объектов, координаты обображает в формате GGMMSS.SSS

**Comment by simgislab** [comment]
да, неплохо было бы чтобы отображение координат в окне атрибутов тоже использовало эту настройку

**Comment by 4eRTuk** [comment]
А какая сборка? Из маркета?

**Comment by simgislab** [comment]
у меня в версии из феи тоже так

https://www.dropbox.com/s/o8nwcdqvjdvpgl2/Screenshot_20160408-171912.png?dl=0

**Comment by simgislab** [comment]
переключил в DD MM.MMM и обратно на DD.DDDDD и все поменялось как надо
