### ISSUE TITLE
созданный geojson имеет не корректные координаты

### ISSUE THREAD

**Issue by ABiatov** [nextgis/android_gisapp#376]
исходный точечный слой "Точки (можно редактировать)" экспортирован через "Поделится" - файловый менеджер.
При открытии в QGIS 2.14 часть точек улетела на север ~на 20 км, трек записанный NGM в формате GPX лег куда наддо.
![smeshenie_chasti_tochek_na_sever](https://cloud.githubusercontent.com/assets/13443276/14348864/3301ac2e-fcd0-11e5-868b-5b53cdc8e461.png)
, а большая часть точек улетела на запад 10 000 км.
![smeshenie_chasti_tochek_na_zapad](https://cloud.githubusercontent.com/assets/13443276/14348870/3c38ff54-fcd0-11e5-83ab-8d213358f1d1.png)
т.е. долгота стала 0, и точки выстроились по гринвичу
![smeshenie_chasti_tochek_na_zapad_x_0](https://cloud.githubusercontent.com/assets/13443276/14349090/96f851be-fcd1-11e5-935d-d9267b44a13e.png)

**Comment by simgislab** [comment]
В NGM показывается правильно?

приложи, пожалуйста, экспортированный слой в тикет

**Comment by ABiatov** [comment]
Да, в NGM правильно.
[Точки (можно редактировать).geojson.zip](https://github.com/nextgis/android_gisapp/files/208223/geojson.zip)
Там не на 0 сбросилось, а ткнуло точку после первого знака в координату X. А чего смещение на север не понял.

**Comment by simgislab** [comment]
у меня вроде нормально всё:

![](http://m-d.me/img/ss/20160307-150335.png)

**Comment by ABiatov** [comment]
Странно. Возможно проблемы с драйвером geojson  gdal в конкретной версии QGIS.

Windows 7, QGIS 2.12.2 GDAL 1.11.3 открыло нормально
а в Xubuntu 14.04, QGIS 2.14.1 GDAL 1.11.2 открыло как на скринах выше, не прочитав координату X из geojson для большенства точек.

**Comment by BishopGIS** [comment]
Да в GDAL 1.x не обрабатывается локаль и все разделители отличный от точки игнорируются (остается только целая часть). Кстати это мы баг исправили в GDAL2. Перелючи локаль цифр на английскую или (С) и все заработает.

**Comment by simgislab** [comment]
@trolleway давай этот кейс добавим в документацию по NGQ и сошлемся из документации NGM. Не первый раз уже возникает.
