### ISSUE TITLE
как соотнести фотографии сделанные через NGM с точками при экспорте в geojson

### ISSUE THREAD

**Issue by ABiatov** [nextgis/android_gisapp#377]
Точечный слой практически на каждую точку имеет фотографии в прицепе.
При экспорте в geojson в атрибутивной таблице в поле "attaches" содержиться колличество фото и назваание фото в папке, например: "(4:10000002.jpg,10000000.jpg,10000001.jpg,10000003.jpg)"
А сами фото располагаются в папках имеющих номер. В каждой папке нумерация начинается с 10000000.
Не понятно, как соотнести фото из attaches с конкретными точками при открытии на десктопе, т.к. все фото имеют +- одинаковое название и номер папки с фото ни где не пишется в атрибутах.

На мобильном же все отображается корректно, каждой точке соответствуют ее фото.

**Comment by BishopGIS** [comment]
У кадого атача должна быть папка с номером в имени. Номер в имени соответсвует id записи (в таблице атрибутов qgis первая колонка).

**Comment by ABiatov** [comment]
Может лучше это вынести в отдельное атрибутивное поле?

**Comment by BishopGIS** [comment]
Я думаю, что это не правильно. Зачем плодить сущности. Есть стандартный идентификатор, который по стандарту должен быть. Зачем заводить поле, которое его дублирует.  Возможно нужно какое-то более элегантное решение.

**Comment by simgislab** [comment]
добавил разъяснения в документацию

https://github.com/nextgis/docs_ngmobile/blob/master/source/share.rst#%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9
