### ISSUE TITLE
Select all в списке треков

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#38]
В списке треков есть кнопка `Select all`, но работает она как инвертирование выделения. Баг?

**Comment by 4eRTuk** [comment]
Ну, вообще так и задумывалось. Обычно в списках эта кнопка работает как select/deselect all.

**Comment by drnextgis** [comment]
Я к тому, что если выбрать часть треков, и нажать эту кнопку, то они перестанут быть выбранными, а выберутся остальные. В логгере такая же кнопка по-другому работает.

**Comment by 4eRTuk** [comment]
Понял тебя, тогда баг конечно.
