### ISSUE TITLE
Не учитываются исправления в параметрах подключения к NGW

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#388]
При создании подключения к NGW, если первый раз ввёл неправильные реквизиты, попытался подключиться, а потом их исправил, то всё равно не пускает - `Ошибка входа`.

**Comment by NikitaFeodonit** [comment]
Проблема в том, что HTTPLoader не пересоздается. То есть при первом нажатии на кнопку Подключить создается HTTPLoader, к конструктор которого передаются url, логин и пароль. А при последующих нажатиях на Подключить этот лоадер не пересоздается, см. документацию на LoaderManager.initLoader() и LoaderManager.restartLoader().

**Comment by BishopGIS** [comment]
На последней версии приложения из феи если ввести в качестве url NGW адрес без http не выполняется подключение.
Например: 176.9.38.120/practice - не подключается, а http://176.9.38.120/practice - подключается.
Должна работать автоподстановка при которой адрес 176.9.38.120/practice при запросе превращается в http://176.9.38.120/practice

**Comment by 4eRTuk** [comment]
Сейчас все именно так и работает. Проверь еще раз.

**Comment by BishopGIS** [comment]
Да, на последней сборке все ок.
