### ISSUE TITLE
Слои с гостевым входом в НГВ не должны создавать в системе аккаунты

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#405]

**Comment by 4eRTuk** [comment]
Это критично? Тогда не будет сохраняться выбранный инстанс, каждый раз при "Добавить из NextGIS" надо будет вводить его имя заново.

**Comment by BishopGIS** [comment]
Там разные есть мнения. С одной стороны подключаю я 100 слоев - получаю 100 аккаунтов.
С другой стороны без аккаунта сейчас не сделать, что бы данные однонаправленно синхронизировались.

Я за то, что бы синхронизацией занимался аккаунт nextgis.com, тогда все логично получается.
А по поводу Добавить из  NextGIS - там надо логику диалога переделывать. Ранее об был так сделан исходя из того что подключений много. Сейчас СААС один.
