### ISSUE TITLE
Падение при начале редактирования

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#407]
Если включен всего один слой, то при начале редактирования открывается панель со всеми активными кнопками.
Любая кнопка кроме "+" приводит к падению приложения.
![screenshot_2016-05-26-09-56-53](https://cloud.githubusercontent.com/assets/1708122/15564973/376967ec-2328-11e6-8af9-f6ded0c77de8.png)

**Comment by 4eRTuk** [comment]
Fix in 3f4f15c1a91bacb4d3d2a51c5ae19f7e4c7e0516
