### ISSUE TITLE
Нарушена последовательность действий редактирования, принятая в 2.3

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#408]
Раньше что бы отредактировать запись необходимо было:
1. Долгим тапом выделить геометрию
2. В открывшемся нижнем баре нажать "карандаш".
3. Изменить геометрию
4. Нажать дискету
5. Изменить атрибуты
6. Нажать галку
Далее можно редактировать или создавать следующую геометрию

В 2.4:
1. Долгим тапом выделить геометрию
2. В открывшемся нижнем баре нажать "карандаш".
3. Изменить геометрию
4. Нажать дискету
5. Нажать кнопку "i"
6. Нажать кнопку "списко"
7. Изменить атрибуты
8. Нажать галку
9. Нажать крестик
10. Нажать карандаш

Итого 4 лишних шага. Причем совершенно не интуитивно понятных.

При создании новой геометрии в 2.3.
1. Вызвать главную кнопку приложения и выбрать "карандаш"
2. Начать редактировать
3. Нажать дискету и ввести атрибуты
4. Нажать галку
5. Начать редактировать новую геометрию

В 2.4.
1. Вызвать главную кнопку приложения и выбрать "карандаш"
2. Выбрать "плюс"
3. Начать редактировать
4. Нажать дискету и ввести атрибуты
5. Нажать галку
6. Нажать "плюс"

Явный регресс в плане юзабилити.

**Comment by 4eRTuk** [comment]
По редактированию и вылезанию окна редактирования атрибутов я помню было много обсуждений, что оно вечно надоедает и его неплохо было бы отключить или иметь такую возможность. И я слабо могу представить чтобы описанный тобою юзер-кейс встречался часто, когда нужно постоянно метаться между редактированием геометрии и редактированием атрибутов.

При создании новой геометрии в 2.3 ты упустил шаг "Нажать кнопку создать новую точку/линию/полигон" - без нее редактировалась бы выбранная геометрия или ничего не редактировалось бы вообще.

**Comment by BishopGIS** [comment]
1. Это стандартный кейс. Например уточнения местоположения остановок общественного транспорта. Надо сдвинуть точку и подправить график и номера маршрутов. Мы этим занимались для дептранса
2. В обоих примерах я правильно указал шаги - 2.4. тоже нет шага Нажать кнопку создать новую точку/линию/полигон

Тут вопрос не в этом. А в том, что стало больше шагов. Поменялся привычный порядок. Обоснование почему так был изменен пользовательский опыт с точки зрения пользователя я не вижу. Вот что конкретно улучшилось для пользователя от того что так сделано?
Мобильное тестировали ОСМеры при сборе подъездов - то что в 2.3 не вызывало нареканий. Все предложения от них я в тикеты перевел.

Считаю что порядок редактирования нужно вернуть или улучшить в сторону юзабилити, если есть предложения - давайте обсудим. Пока, как я отметил, юзабилити усложнилось.

**Comment by simgislab** [comment]
надо обсуждать

**Comment by simgislab** [comment]
не обсудили, так закрыли, молодцы, отличная работа

**Comment by simgislab** [comment]
и я молодец :)
