### ISSUE TITLE
"Ошибка, соединение не установлено" при подключении к nextgis.com, когда сменился пароль.

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#411]
Создал подключение к nextgis.com. Добавлял слои.
Через 2 дня инстансы перезапустили, пароль ngw изменился.
В мобильном пытаюсь добавить слой из Nextgis. В списке аккаунтов нажимаю на свой. 
Выводится "Ошибка, соединение не установлено"

**Comment by trolleway** [comment]
Нашёл в другом месте программы окно изменения пароля Nextgis. После изменения пароля всё подключается. 
В этом случае нужно выводить сообщение об ошибке: "Неправильный пароль"

**Comment by BishopGIS** [comment]
Мобильное не знает пароль не правильный или что-то еще не так. Закрываю, раз все получилось.
