### ISSUE TITLE
Send unconnected layer to nextgis.com

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#412]
1. User creates a layer
2. Edits it
3. Wants to have it on his nextgis.com Web GIS

**Comment by BishopGIS** [comment]
Application don't know now witch of 100500 nexgisweb accounts in application can receive unconnected layer.
Some permissions must be checked.
May be some dialog must offer user's nextgis.com instance first (need #413), and than some additional instances where user have write permissions.

**Comment by 4eRTuk** [comment]
Advanced mode (may be switch control) would be useful too (for different NGW instance, not nextgis.com), I think.

**Comment by simgislab** [comment]
don't quite understand what is the difficulty here:

1. User creates a layer
2. Edits it
3. Select Share or Send to nextgis.com
4a. Typical case - user doesn't have an instance - he is asked to create one
4b. Typical case - user has one instance - it isautomatically selected as target
4b. Rare case - user he has several instances - he is asked which one and where to put new layer

**Comment by BishopGIS** [comment]
On premis and nextgis.com accounts mast be separated first. Now it is
complicated and unlogical.

**Comment by simgislab** [comment]
again, I don't see a problem. Our typical user is:

a. Has one Web GIS
b. This Web GIS is at nextgis.com

Current process for this user is neither complicated nor unlogical.

**Comment by BishopGIS** [comment]
There is no problem, but still exists mixing of standalone NGW and nexgis.com. This fprm a lot of problems, unlogical dialogs and windows with switches, internal complicated and etc. I only note, that before releasing this functionality, splitting NGW accounts and nextgis.com account is highly recommended.
