### ISSUE TITLE
Add nextgis.com integration

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#413]
Need nextgis id and nextgis.com account settings in application options:
- [ ] create account
- [ ] create instance
- [ ] see and change instance properties
- [ ] other services linked with account
- [ ] register current device in account (for sendto functionality and etc.)

**Comment by simgislab** [comment]
waiting for special my.nextgis.com service from @yellow-sky

**Comment by simgislab** [comment]
не понимаю зачем это надо было закрывать

**Comment by 4eRTuk** [comment]
Fixed in b8485ace96418395b90a45d08e393fc774ef08b3
