### ISSUE TITLE
Incorrect zoom to extent behavior for NGRC

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#420]
Example: https://www.dropbox.com/s/h1hbgbg5035fkra/project.ngrc?dl=0

1. Add as local
2. Zoom to extent

**Comment by BishopGIS** [comment]
Это не тоже самое #389 ?

**Comment by 4eRTuk** [comment]
Looks like everything is fine. The smallest zoom level is 5, and there is only one tile  https://www.dropbox.com/s/nh6mdrzq1vpqqrs/10.png?dl=0
It has small dot and transparent background near it, so it zooms to full tile for zoom 5.

**Comment by simgislab** [comment]
yes, all is fine
