### ISSUE TITLE
Не работает ручная синхронизация

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#425]
Добавили слой из веба.
Включили его в синхронизацию. Автоматическая синхронизация - выключена.
Вносим изменения в слой в мобильном. 
Нажимаем кнопку "Синхронизация" - синхронизация идёт, но в вебе запись не меняется.
После включения автоматической синхронизации запись в вебе меняется.

**Comment by BishopGIS** [comment]
Я так понимаю, что пока не посталена галка в настройках, вообще не вызывается onsync. 
Попробуй воспроизвести.

**Comment by 4eRTuk** [comment]
У меня вызывается и синхронизируется.

**Comment by simgislab** [comment]
странно, но я теперь тоже не могу воспроизвести (автосинхронизация отключена, слой включен, все ок), я правда обновился

@trolleway попробуй еще раз и закрой если не воспроизводится

**Comment by simgislab** [comment]
проверил еще раз, синхронизируется и вручную тоже
