### ISSUE TITLE
Не прикрепляется фото с SD-карты

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#432]
В твиттер через системный пикер можно загрузить фото с карточки, у нас - нельзя.

**Comment by 4eRTuk** [comment]
Можно, если системный пикер установлен и выбрать "Показать SD-карту".

**Comment by trolleway** [comment]
В пикере оно выбирается, но потом на экране показывается таблица атрибутов нашего приложения, и надпись "Невозможно прикрепить фото"

**Comment by 4eRTuk** [comment]
Какая версия андроида, со всеми фотками так? Если нет, то скинь пример фото.

**Comment by trolleway** [comment]
Это со всеми фото с карточки, приложение не может получить доступ к карточке. Версия 5.1.

**Comment by 4eRTuk** [comment]
Должно работать.
