### ISSUE TITLE
В окне добавления фото нужно рисовать крестики на фото с обводкой

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#433]
Если загрузить фотографию снятую летом на улице, то голубой крестик не виден на фоне голубого неба, когда смотришь на экран на солнце
![screenshot_2016-06-29-16-07-32 1](https://cloud.githubusercontent.com/assets/4630662/16452982/d0d5151a-3e13-11e6-9ae7-27c0fa12c011.png)

**Comment by BishopGIS** [comment]
Нужно крестик на фоне выводить - белый полупрозрачный квадратик или кружок.
