### ISSUE TITLE
Трек не продолжает записываться после отключения

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#435]
Записывал трек. Телефон разрядился, после того как его включил - в меню есть пункт Остановить запись трека, хотя он при этом не пишется: не горит человечек сверху и не рисуется на карте. Чтобы заработало - надо остановить и запустить заново.

**Comment by 4eRTuk** [comment]
Какое должно быть ожидаемое поведение после перезагрузки телефона? Остановка трека или его автоматическое продолжение?

**Comment by drnextgis** [comment]
Как минимум если он сейчас не продолжает запись, то надо убрать кнопку Остановить.

**Comment by 4eRTuk** [comment]
Это очевидно. А как максимум?

**Comment by drnextgis** [comment]
@BishopGIS как считаешь?

**Comment by BishopGIS** [comment]
По хорошему должна быть настройка "продолжать запись трека после перезагрузки", выключенная по-умолчанию.
А пока я бы поправил индикацию кнопки записи, что бы она реальный статус показывала.
Возможность настройки отнес к 2.5.

**Comment by 4eRTuk** [comment]
Добавил сразу настройку. С индикацией небольшая неоднозначность, потому что сервис система может убить. Поэтому сейчас она определяется как завершен трек или нет. После перезапуска учитывается настройка, если убит системой - то сервис сам должен перезапуститься.
