### ISSUE TITLE
Два трека с одинаковым именем

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#440]
В мобильном есть 2 трека за одно число: `2016-07-03-1`. Первый вопрос - это нормально, что разные треки имеют одинаковое имя? Второй вопрос - когда я выбираю их оба и пытаюсь сохранить, то сохраняется только второй - это ожидаемое поведение?

**Comment by 4eRTuk** [comment]
Нет, не нормально. У тебя как-то неправильно сохранились треки, отсюда и неработающий экспорт.

**Comment by drnextgis** [comment]
Как-то так: 

![74113](https://cloud.githubusercontent.com/assets/866124/16894127/78af7cc4-4b77-11e6-8a50-a4c937954704.png)
