### ISSUE TITLE
Rules are not saved on setting and exit

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#453]
1. Set few rendering rules for a layer
2. Close the dialog to go to the map
3. Go back to rules editing 

Only one of several rules will be present, all the others are not saved

**Comment by 4eRTuk** [comment]
Does it happen in latest build? Looks like all fine, except list height was only one row, so only one row was visible on screen. Should be fixed already.

**Comment by simgislab** [comment]
now it's fine
