### ISSUE TITLE
Окно идентификации не читабельно

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#455]
![screenshot_2016-07-17-07-50-00](https://cloud.githubusercontent.com/assets/866124/16898096/4045bff2-4bf3-11e6-8e57-36cd76828999.png)

**Comment by drnextgis** [comment]
А если телефон перевернуть, то атрибуты вообще не отображаются.

**Comment by 4eRTuk** [comment]
тема в приложении темная используется?

**Comment by drnextgis** [comment]
Да.

**Comment by 4eRTuk** [comment]
Почему пропадают непонятно. Нужны логи.

**Comment by BishopGIS** [comment]
У меня воспроизводится:
1. Подключаемся как гость к http://rykovd.nextgis.com
2. Подключаем векторный слой  Main resource group -> Altai Republic (July 2016) -> 2016-07-04-1 tracks
3. Открываем таблицу атрибутов вертикально
4. Поворачиваем - пустой экран

**Comment by drnextgis** [comment]
А можно эти бордеры отключить?

**Comment by BishopGIS** [comment]
Если отключить будет не очень читаемо, но вот сделать границы ячеек не трехмерными и в 1-2 px (плоский material design) было бы неплохо.
