### ISSUE TITLE
Обновить копирайт в окне About

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#458]
Сейчас там 2012 - 2015. Да и вообще по исходному коду можно автозаменой пройтись.

**Comment by simgislab** [comment]
fixed https://github.com/nextgis/android_gisapp/compare/79b85e5d95...5a36c9c3a2

**Comment by 4eRTuk** [comment]
Поменял. Мне казалось что дата в исходном коде меняется только когда меняется исходный код.

**Comment by simgislab** [comment]
правильно
