### ISSUE TITLE
Работа с  мультилиниями

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#49]
Создание. удаление, изменение мультилиний

**Comment by 4eRTuk** [comment]
Сейчас при редактировании подсвечивается вся мультилиния целиком. Стоит ли как-то выделять текущую активную линию (сейчас выделяется только выбранная точка), чтобы было понятно какая линия удалится при нажатии на "Удалить линию"?

**Comment by BishopGIS** [comment]
Да это было бы удобно.

**Comment by simgislab** [comment]
т.е. сейчас при удалении удаляется часть мультилинии, а не она вся?

**Comment by 4eRTuk** [comment]
есть отдельная кнопка "удалить мультилинию" и "удалить линию".

**Comment by simgislab** [comment]
тогда все круто!
