### ISSUE TITLE
Form open error

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#500]
> На днях создавал форму для сбора данных при помощи nextgis.com форму создавал formbuilder-ом котоый сейчас на сайте выложен. Данные в NextGIS.com заливал при помощи NextGIS Connect. Но при открытии созданной формы на мобильных устройствах NextGIS Mobile добавляет слой в список слоев, ставит точку, но при открытии формы для вноса атрибутов возвращает сообщение, что "не удалось создать форму" и открывается форма, в которой видно только первое поле "Дата" и подпись идущая после нее, далее ничего нет.

> Где косяк, в формбилдере, NGM, NextGIS Connect, nextgis.com или какая другая причина? Ошибка создания формы воспроизводится на разных устройствах и разных версиях NGM ( поставленный из марета и из тестфери).

> В итоге данные собрали, добавив нужный слой в проект при помощи "добавить из NextGIS" но все пришлось вбивать вручную. 

via Anton Biatov

**Comment by BishopGIS** [comment]
Изменить расширение на ngfp
[old_trees.ngfp.txt](https://github.com/nextgis/android_gisapp/files/467293/old_trees.ngfp.txt)

**Comment by 4eRTuk** [comment]
Проблема в файле ngfp:
```
    {
      "attributes" : {
         "allow_adding_values" : true,
         "field" : "SPECIES",
         "input_search" : false,
         "last" : true,
         "ngw_id" : -1,
         "values" : null
      },
      "type" : "combobox"
   }
```

**Comment by BishopGIS** [comment]
@4eRTuk  Переводи на FB тогда. Репортер же написал, что везде использовал последние версии ПО. Пусть @MikhanGusev посмотрит.

**Comment by 4eRTuk** [comment]
This issue was moved to nextgis/formbuilder#106
