### ISSUE TITLE
При отправке слоя в NextGIS пропадают данные

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#508]
**Имя слоя:** _mpnt_
**Тип геометрии:** _Мультиточка_
**Поля:** _(i, Целочисленное)_, _(dtime, Дата и Время)_

Создаю один объект, состоящий из 3-х точек и заношу атрибут _i=123_, атрибут _dtime_ оставляю по умолчанию. Смотрю атрибуты - всё на месте. Выбираю _Отправить в NextGIS_, указываю свой инстанс. Смотрю на инстансе - слой есть, а запись потерялась по дороге.

Иногда записи нормально доходят, а иногда вот так - теряются. В чём причина?

**Comment by simgislab** [comment]
подтверждаю, слой создался, а записей нет

включить слой на синхронизацию и нажать синхронизовать не помогло

**Comment by drnextgis** [comment]
Если уже после того как слой был отправлен в NextGIS, добавить в него записи и попытаться синхронизироваться, то запись пропадёт и с мобильного и на инстансе не появится.

**Comment by 4eRTuk** [comment]
Только с мультиточками наблюдается? или любой слой? Не могу воспроизвести...

**Comment by drnextgis** [comment]
На точечном попробовал с такой же комбинацией полей - аналогичная картина.

**Comment by 4eRTuk** [comment]
@drnextgis @simgislab проверьте сейчас, должно работать.

**Comment by drnextgis** [comment]
Сейчас гляну, отпишусь.

**Comment by drnextgis** [comment]
Попробовал - всё работает, в чем была проблема?
