### ISSUE TITLE
На маленьком экране в диалоге загрузки тайлов не видны цифры

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#509]
![img_20160920_120454](https://cloud.githubusercontent.com/assets/4630662/18664438/3645f114-7f2b-11e6-874b-9533d679720f.jpg)

**Comment by 4eRTuk** [comment]
@trolleway Проверь теперь.

**Comment by trolleway** [comment]
Проверили, но осталось
![img_6370](https://cloud.githubusercontent.com/assets/4630662/20177026/ac822db8-a75b-11e6-857c-61a032384e5e.JPG)
