### ISSUE TITLE
Работа с мультиполигонами

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#51]
Создание, изменение, удаление мультиполигонов
При выборе действия «редактировать геометрию» должны подсвечиваться узлы геометрии. В этом режиме Пользователю открывается возможность переместить узловую точку путем ее нажатия и смещения.

**Comment by simgislab** [comment]
а это все-таки про полигоны или сразу мульти? По описанию - просто полигоны.

**Comment by BishopGIS** [comment]
Полигоны (#50) надо по ТЗ РЛЗ делать, а мульти - нет. Поэтому тут нет ни milestone ни точного описания.
