### ISSUE TITLE
Неверные координаты в GeoJSON

### ISSUE THREAD

**Issue by inquartatech** [nextgis/android_gisapp#525]
[4342504.5,5621083] - Это я не понимаю, что за цифры

`{"features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[4342504.5,5621083]},"properties":{"FID":123,"attaches":[],"TEXT":"gghjkk"}}],"type":"FeatureCollection","crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::3857"}}}`

Android 4.2

**Comment by BishopGIS** [comment]
Координаты верные. В файле определена СК - см. {"name":"urn:ogc:def:crs:EPSG::3857"} что означает что координаты даны в СК Web Mercator.
Формулы перевода простые. Все нормальные ГИС понимают такой формат.
