### ISSUE TITLE
Автоматическая синхронизация слоя с сервером по умолчанию

### ISSUE THREAD

**Issue by RuslanKiselev** [nextgis/android_gisapp#527]
При добавлении новой формы в мобильное приложение, необходимо по умолчанию включать автоматическую синхронизацию с сервером веб-гис. при добавлении выдавать всплывающее окно предупреждение , что на добавленной форме по умолчанию включена автоматическая синхронизация и это может приводить к повышенному потреблению заряда из батареи, функцию можно отключить или перевести в ручной режим синхронизации перейдя в настройки добавленного слоя.

**Comment by trolleway** [comment]
А что если просто при добавлении слоя из веба, или формы связанной с вебом, выводить пользователю вопрос: "Синхронизировать?"

**Comment by RuslanKiselev** [comment]
Артем это рискованно, так как пользователь может не знать слово синхронизация. Он просто хочет, что бы собранные им данные появлялись на веб карте. А когда станет опытным пользователем, он уже сам сможет под себя все настраивать.

**Comment by simgislab** [comment]
>Он просто хочет, что бы собранные им данные появлялись на веб карте
Это и есть синхронизация

**Comment by 4eRTuk** [comment]
Мне нравится предложение Артема. Делаю так?

**Comment by RuslanKiselev** [comment]
Хорошо. Тогда всплывающее окно с выбором из трех позиций: автоматически, вручную, не синхронизировать

**Comment by simgislab** [comment]
@4eRTuk давай так, да
