### ISSUE TITLE
Непонятно, задан ли пароль от веба, или нет

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#528]
# Шаги для воспроизведения
Создать в formbuilder форму работающую с новым аккаунтом в NGW, положить её на мобильное, в котором нету подключения к этому инстансу

# Текущее поведение
В мобильном нельзя понять: записан ли пароль к подключению.
![screenshot_2016-10-04-13-59-56_com nextgis mobile](https://cloud.githubusercontent.com/assets/4630662/19071877/f2bb3a9c-8a3a-11e6-8bc9-3576bf9393ea.png)

# Ожидаемое поведение
В поле пароля на этом экране должны быть звёздочки/точки, или же под ним должна быть надпись: "Пароль задан/Пароль не задан"

**Comment by 4eRTuk** [comment]
Fix in 6cb29fd62cff140773186bf9fa9e2039cf8d5984
