### ISSUE TITLE
[Feature request] Возможность удалить все данные векторного слоя

### ISSUE THREAD

**Issue by MaksVasilev** [nextgis/android_gisapp#535]
Прошу добавить в настройках векторного слоя возможность удалить все его объекты. Логично расположить это в "настройки слоя" -> "общие". Удаление с подтверждением, на всякий случай.

Это нужно потому, что очень часто (у меня вообще всегда) сбор данных происходит поэтапно: часть данных собрана -> отправлена в виде geojson на сервер, там обработана и добавлена в базу к предыдущим данным. После этого новая партия данных  собирается уже с чистого листа, что бы не гонять в обработку данные собранные в прошлые разы и прошлые года.

**Comment by simgislab** [comment]
@MaksVasilev просьба протестировать

**Comment by MaksVasilev** [comment]
Подскажите, где нужно брать сборку, что бы протестировать этот коммит? У меня стоит с гугл-плея.

**Comment by simgislab** [comment]
https://tsfr.io/mtt3jt

**Comment by MaksVasilev** [comment]
Спасибо, обязательно проверю, но сейчас я в аэропорту сижу и немного ограничен в возможностях тестирования. Доберусь до цивилизации 15.12 вечером, постараюсь 16.12 до обеда отписаться.

**Comment by MaksVasilev** [comment]
Проверил, работает, никаких неожиданностей и ошибок не возникло. Спасибо.
