### ISSUE TITLE
Добавление в пользовательские формы новых элементов

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#54]
1. Закладки (табы)
2. checkbox
3. button
4. group
5. space
6. orientation
7. compass
8. Поле управления вводом координат (для точек)

**Comment by simgislab** [comment]
@4eRTuk можешь написать что сделано? Остальное разнести по отдельным тикетам и закрыть этот.

**Comment by 4eRTuk** [comment]
1. решили не делать
2. сделано
3. #210 
4. #211 
5. сделано
6. решили не делать
7. #212 
8. сделано
