### ISSUE TITLE
не грузятся растровые слои из nextgis.com

### ISSUE THREAD

**Issue by ABiatov** [nextgis/android_gisapp#540]
NGM 2.4.2. (rev.18)
Растровый слой появляется в списке слоев но не отображаются на карте. "Загрузить тайлы"  не помогает.

![screenshot_2016-11-17-07-14-03](https://cloud.githubusercontent.com/assets/13443276/20379960/b5721b94-aca7-11e6-9a55-10252f2144e7.png)

![screenshot_2016-11-17-07-14-40](https://cloud.githubusercontent.com/assets/13443276/20379919/69739286-aca7-11e6-97b5-24a816c8231f.png)

В то же время этот же растровый слой подключен на веб-карту. И если вебкарту подключить как растр, тогда отображает.

 ![screenshot_2016-11-17-07-13-13](https://cloud.githubusercontent.com/assets/13443276/20379845/14bf2b06-aca7-11e6-8c0d-5ac5a19d585e.png)

Векторные слои подключенные как растр отображаются нормально.

![screenshot_2016-11-17-07-16-52](https://cloud.githubusercontent.com/assets/13443276/20379983/d2018736-aca7-11e6-8f5b-3580d96757f3.png)

**Comment by simgislab** [comment]
Стиль у растра который не показывается создан?
Приложи, пожалуйста, название Веб ГИС еще.

**Comment by ABiatov** [comment]
У всех растров стиль создан.

не грузится не один из этих растров
http://gis-naturalist.nextgis.com/resource/61
только вебкарта грузится как растр.

Этот растр тоже не грузится, хотя раньше грузился 
http://gis-naturalist.nextgis.com/resource/6

**Comment by simgislab** [comment]
у меня один из растров без проблем загрузился и показывается

(пруф)[https://www.dropbox.com/s/43yf2rcu6tk9ed1/Screenshot_20161117-115551.png?dl=0]

**Comment by ABiatov** [comment]
У тебя та же версия NGM ?

**Comment by 4eRTuk** [comment]
Fix in 4dad5b459b8e4c8fd80e932c59be8ba9754dbd0c

**Comment by simgislab** [comment]
@ABiatov, 2.4.2 (rev. 18) отсюда https://tsfr.io/mtt3jt 

если ты не менял источник последнее время, то лучше переставь по ссылке выше, мы изменили репозиторий, старый больше не работает

**Comment by ABiatov** [comment]
Спасибо.
Переставил, предварительно счистив весь кеш карт и заработало.
