### ISSUE TITLE
Создать возможность односторонней синхронизации (отправки данных в облако)

### ISSUE THREAD

**Issue by ABiatov** [nextgis/android_gisapp#543]
Создать возможность отправки данных в облако. т.е. собранные данные улетают в nextgiscom, но изменения из nextgiscom в NGM не загружаются. Как мне кажется, данный функционал мог бы в некоторых случаях предупредить потерю данных, как описанно тут https://github.com/nextgis/android_gisapp/issues/542
Данный функционал полезен также когда работает несколько полевых работников, фотографируют большое количество фотографий и прикрепляют их как вложения к собранным геоданным. И нужно чтоб их собранные данные отправлялись в облако, но не нужно каждому загружать собранные другим данные и забивать файловую систему мобильного устройства массивамии чужих полевых фотографий.

Предложение по реализации:
В NGM в настройках NextGIS в настройках синхронизации слоев добавить чекбоксы напротив каждого слоя: "двухстороняя синхронизация" (как сейчас) и "отправлять изменения в облако",  и "получать изменения из облака"

**Comment by simgislab** [comment]
@ABiatov просьба протестировать
