### ISSUE TITLE
Clear tile cache for selected layer

### ISSUE THREAD

**Issue by KEFIR666** [nextgis/android_gisapp#544]
Очень неплохо было бы иметь возможность очистить текущий кеш слоя. Например, для случаев, когда изменяется содержимое WMS (в основном речь про самостоятельно добавленные слои).

**Comment by MaksVasilev** [comment]
Присоединяюсь к запросу. Вырезать с файловой системы кеш не всегда удобно, а реализация такой функции в самой программе сильно облегчит работу в поле с постоянно обновляемыми слоями.

p.s. про очистку векторных слоёв, тоже пожалуйста не забудьте: https://github.com/nextgis/android_gisapp/issues/535

**Comment by simgislab** [comment]
Добавить кнопку
Свойства слоя - Кэш - Очистить
