### ISSUE TITLE
Count number of tiles to be downloaded

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#546]
Calculate and show number of tiles to be downloaded according to current settings.

Abbreviate numbers to M and B, e.g. 10M instead of 10239878 etc.

**Comment by 4eRTuk** [comment]
Do you mean when importing local raster zip? Tile downloading is in background (in notification).

**Comment by simgislab** [comment]
no, on caching a service locally, BEFORE download button is hit
