### ISSUE TITLE
Show scale next to zoom levels at tile caching dialog

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#547]
currently:
min: 8    max: 15

should be:
min: 8 (20 km)    max: 15 (150 m)

http://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by 4eRTuk** [comment]
Show scale per pixel?

**Comment by simgislab** [comment]
this is too much, zoom level + scale is enough

**Comment by simgislab** [comment]
Add the same additional info here too:

![](http://m-d.me/img/ss/20161206-wp0-37kb.jpg)
