### ISSUE TITLE
Show name of the layer instead of geometry type in layer properties heading

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#553]
Right now it says Point which is not very helpful. May be show layer name there.

Add geometry type indication to General options.

**Comment by 4eRTuk** [comment]
Maybe move geometry type to subtitle?

**Comment by simgislab** [comment]
good idea, may be like this:
Features: 63 (points)
Объектов: 63 (точки) <- let's fix the translation here too 'запись' is jargon
