### ISSUE TITLE
Поле ИД

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#554]
Мне кажется или id автоматические переводится в ИД? Это странно выглядит. Я бы предложил не переводить. Поле наверняка как-то по другому называется?

![](http://m-d.me/img/ss/20161206-8w5-18kb.jpg)

**Comment by 4eRTuk** [comment]
Да, автоматически. Само поле _id

**Comment by simgislab** [comment]
давай лучше так и показывать

**Comment by simgislab** [comment]
туда же, в информации о точке название поля вообще куда-то пропадает

![](http://m-d.me/img/ss/20161206-b06-17kb.jpg)
