### ISSUE TITLE
Polygon labels stopped working

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#566]
Test data: https://www.dropbox.com/s/46lxof43ef5z59x/%D1%81-%D0%B7%20%D0%95%D1%80%D1%88%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9.geojson?dl=0

**Comment by 4eRTuk** [comment]
Fix in 94765328866e4c5e3977116cb852500afd36a938
