### ISSUE TITLE
What happens if two controls are connected to the one field on the form

### ISSUE THREAD

**Issue by MikhanGusev** [nextgis/android_gisapp#571]
Original message:
> Actually what happens in mobile app is this. If I skip Combo1 and I put a value in Combo2, Combo1 is not valorized but the app accepts saving and next time if I show vector info both combos are valorized. If I put a value in Combo1 and skip Combo2 then I save, the app gives message 'value is not from list' and saves, but when I show vector info there is no value in linked layer's field, and both combos are not valorized.

For me in all cases the value from the second (the last) combo was saved, which seems logical. There was no message 'value is not from list'. The proposal is to handle such situations so the user can select the value from the one combo and deselect from another.

**Comment by plinioconti** [comment]
Hi, 
please see the the test case in issue #570 

Use the same CSV, FORM, and the same two comboboxes ("NOME SCIENTIFICO" and "NOME COMUNE")

**Comment by MikhanGusev** [comment]
Yes, I reproduced the case with this form. I think this is not a bug but some behavior. @4eRTuk what we can do with this? How we can handle the case when two controls on the form are assigned to the one field?

**Comment by 4eRTuk** [comment]
I think we should not allow this.

**Comment by plinioconti** [comment]
Just think to the case you want to select an item in list using sometimes the key (ex. product code), sometimes the displayed value (ex. Product name).

It is not so unusual!

**Comment by 4eRTuk** [comment]
You could use alias like "Code (name)" and keep value as is.

**Comment by plinioconti** [comment]
yes. that is a workaround, but not always so good.

What if the list is long? maybe you would sort "key" and "displayed" in two different lists (combobox) to easy find the item.

Or think in my case, I have "key" and "displayed" are both text values, they are not short.
They are both plant names (botanic and common name). It's hard to have both texts in the same line on a mobile device!

**Comment by simgislab** [comment]
After another round of discussions, here is what we are going to do:

1. Formbuilder changes
We're introducing the new control - Double combobox (tentative name). Places two comboboxes and two labels for them. Set the following parameters:

- label 1
- values 1 and 2
- label 2
- field
- 'allow adding values'

2. Mobile changes
If mobile sees such control, then when something is selected in on in the field1 will lead to appropriate selection in the field 2.
But if something NEW is entered in one the fields and  'allow adding values' was ON, then it is added like usual and automatically transfered to another combobox as well.

So you can't choose two values with different inners at all.

**Comment by plinioconti** [comment]
Yes, it sounds good, but I am not sure I understand. Can I see / test it?

**Comment by simgislab** [comment]
We need to choose one way or another, before starting to implement it. So there is nothing to try yet.

First one is simply the way to combine Latin and Local names in one column, so you'll be able to type/select any. No need to have two fields.

Second one is more work, we'll need to add a special control for that.

**Comment by plinioconti** [comment]
It would be great to have two different fields, if possibile.

Il 13 lug 2017 8:45 PM, "Maxim Dubinin" <notifications@github.com> ha
scritto:
