### ISSUE TITLE
При вводе полигонов обходом не фильтруются выбросы, получаются самопересечения, из-за этого фичи не сохраняются

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#575]
Шаги для воспроизведения:
1. Включить ввод полигонов обходом.
2. Обойти вокруг офиса
3. Нажать Save

Ожидаемое поведение:
Выбросы отрежутся, или фича сохранится с 8-образной геометрией

Фактическое поведение:
Фича не сохраняется, ходил зря.

![screenshot_2017-07-25-16-33-11_com nextgis mobile](https://user-images.githubusercontent.com/4630662/28574752-7f354c2a-7157-11e7-81e1-e0694c83498c.png)

**Comment by BishopGIS** [comment]
> Очень бы пригодилась фильтрация ошибочных точек трека. При высокой частоте измерений местоположения трек иногда отбрасывает на огромные расстояния ошибочным измерением. В дальнейшем это затрудняет работу с треком, даже просто в OSM такие данные лучше не загружать. Было бы очень замечательно, если бы не фиксировались измерения, значения которых превышают три стандартных отклонения от предшествующих измерений.

http://xn--80afd3balrxz7a.xn--p1ai/chem-ploh-nextgis-mobile/
