### ISSUE TITLE
Ошибка добавления локального слоя - "CRC mismatch"

### ISSUE THREAD

**Issue by Saltuarius** [nextgis/android_gisapp#578]
В последней версии v. 2.5.6.2 (rev. 27) невозможно добавить слой (.zip) из локального хранилища устройства. Выдает ошибку "CRC mismatch". В одном файле на 2%, во втором - на 37%.

**Comment by simgislab** [comment]
приложите слой

**Comment by 4eRTuk** [comment]
Fix in c22608aa4231c89f798d54fe1b4b202a56fcd72b
