### ISSUE TITLE
Ruler is not working

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#584]
http://xn--80afd3balrxz7a.xn--p1ai/chem-ploh-nextgis-mobile/

> После обновления в начале августа перестало работать измерение расстояний. Все излечилось установкой apk-файла с сайта nextgis.ru, но в начале сентября и по сей день линейка опять не работает.

**Comment by simgislab** [comment]
duplicate of #576 

слепое копирование - плохо
