### ISSUE TITLE
Добавить инструмент измерения расстояния и площади

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#59]

**Comment by 4eRTuk** [comment]
Как реализовать работу с ним?

**Comment by BishopGIS** [comment]
Я предлагаю как в яндекс картах. Только само расстояние должно в нижнем тулбаре выводиться.

**Comment by 4eRTuk** [comment]
А как в яндекс картах? Я что-то не могу найти как там измерить расстояние.

**Comment by BishopGIS** [comment]
Иконка линейки слева внизу.

**Comment by 4eRTuk** [comment]
Где бы ее в ландшафтном режиме расположить?

Сейчас на 4" интерфейс выглядит так, кнопку там некуда вставить:
https://www.dropbox.com/s/rpxqvatc9uwf3e0/Screenshot_2016-02-13-16-01-00.png?dl=0

**Comment by simgislab** [comment]
вверху справа напрашивается

**Comment by BishopGIS** [comment]
Не надо в статусе - эта панель может быть выключена в настройках. Инструментарий от настроек не должен зависеть.

**Comment by simgislab** [comment]
а где увидеть эти инструменты? пока не нашел что-то

**Comment by 4eRTuk** [comment]
Кнопка справа вверху на карте.

**Comment by simgislab** [comment]
появилась

я правильно понимаю что она пока только длину линии измеряет?

еще, при повороте экрана отмеченная линия пропадает

**Comment by 4eRTuk** [comment]
Пока да. Думаю для площади соединять пунктиром первую/последнюю точки и выводить в подзаголовок.
