### ISSUE TITLE
The ruler does not work on the map

### ISSUE THREAD

**Issue by ABiatov** [nextgis/android_gisapp#599]
NGM v.2.5.6.2 (rev. 27)

![screenshot_20171015-142335](https://user-images.githubusercontent.com/13443276/31584388-fe717ac4-b1b5-11e7-9958-22a6882e200f.jpg)

![screenshot_20171015-142345](https://user-images.githubusercontent.com/13443276/31584387-fe51afaa-b1b5-11e7-8460-86ed4ab44dc4.jpg)

Жму, жму и ничего не происходит.

![screenshot_20171015-142350](https://user-images.githubusercontent.com/13443276/31584386-fe2d434a-b1b5-11e7-8661-2852d45d81d3.jpg)

**Comment by simgislab** [comment]
обновись, это как раз чинили недавно, у тебя старая версия мобайла
https://github.com/nextgis/android_gisapp/issues/576

если все так же не работае - переоткрывай

**Comment by strobilurus** [comment]
Подтверждаю баг!

**Comment by simgislab** [comment]
версия мобайла какая?

**Comment by ABiatov** [comment]
Обновился из Плеймаркета, все заработало

**Comment by strobilurus** [comment]
v. 2.5.6.5 (rev. 30). Аналогично, принудительно обновился, - все в норме! Спасибо!
