### ISSUE TITLE
Пропускаются события отрисовки последнего слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#6]
Если пропущено события отрисовки последнего слоя (вся карта отрисована), то не происходит обновления экрана. Карта показа не полностью, но стоит сдвинуть, сразу же картинка обновляется.

**Comment by drnextgis** [comment]
Я не знаю к этому это относится или нет, но при pan-е если на это место нет тайлов, то они не отображаются, если пошевелить карту - тогда появляются.
![screenshot_2015-02-04-09-19-35](https://cloud.githubusercontent.com/assets/866124/6034626/cc16be76-ac46-11e4-8cc5-f2b8cf718a3b.png)

**Comment by BishopGIS** [comment]
Поставлю таймаут по-больше на скачку тайлов.
