### ISSUE TITLE
Camera can´t be activated on Android 7

### ISSUE THREAD

**Issue by KamilSvoboda** [nextgis/android_gisapp#603]
There is no way to activate a camera from NextGIS Mobile running on Android 7 to be able to add attachment to the vector feature. Behavior on Android 6 or older has been correct.

**Comment by simgislab** [comment]
version of the app?

**Comment by KamilSvoboda** [comment]
2.5.6.3 (rev. 28)

**Comment by simgislab** [comment]
you're quite behind, please update often, we're doing lots of bug-fixing recently

reopen if issue is still there in latest version

**Comment by KamilSvoboda** [comment]
ok, thank you for a quick reply!
