### ISSUE TITLE
Корректный URL не проходит проверку в maplib

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/android_gisapp#604]
Проблема возникает с некоторыми URL в этой точке:

https://github.com/nextgis/android_maplib/blob/57b650aa903e9b6cdf4da73f99d29a877f9de804/src/main/java/com/nextgis/maplib/util/NetworkUtil.java#L145

Валидатор android.util.Patterns.WEB_URL.matcher() не пропускает, например, такой URL, который открывается в браузере:

http://kedr.primorsky.ru/ngw/api/resource/57/feature/?bbox=14837293.000000,5535483.500000,14980318.000000,5692577.000000&status=%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9&date={%22gt%22:%222017-06-18T00:00:00Z%22}

На этот валидатор уже были нарекания:
https://stackoverflow.com/a/29771086
Рекомендуют его вовсе не использовать, заменив на альтернативный.

**Comment by jekhor** [comment]
Аналогично, из-за этого же валидатора не проходит валидация URL в диалоге подключения к NextGIS Web для URL http://gis.minsk.bike/ — как минимум, старые версии этого валидатора не знают о домене .bike.
Место в коде: https://github.com/nextgis/android_maplibui/blob/master/src/main/java/com/nextgis/maplibui/fragment/NGWLoginFragment.java#L200

**Comment by BishopGIS** [comment]
Подозреваю что URL вводится не в то поле. Есть "зачем-то" заныканая опция для ввода кастомных url для Web-GIS

http://docs.nextgis.ru/docs_ngmobile/source/load_geodata.html#ngmobile-conversation-connection-webgis-pic

Внизу см ``Нажми сюда``

**Comment by jekhor** [comment]
Да, естественно.

**Comment by jekhor** [comment]
Да, на 7 андроиде работает.
