### ISSUE TITLE
Не открывается диалог выбора локального слоя

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/android_gisapp#605]
При нажатии на пункт меню "Открыть локальный" выскакивает уведомление, диалог не открывается. Непонятно, что именно должно быть включено в Настройках.

Телефон - Xiaomi Redmi Note 4.
OS - MIUI 9.2.2.0 (Android 6.0)

![screenshot_2018-01-30-16-39-07-898_com nextgis mobile](https://user-images.githubusercontent.com/6493848/35569434-1c9e6a7c-05dd-11e8-9d81-af4eb4af81f3.png)
![screenshot_2018-01-30-16-41-51-574_com nextgis mobile](https://user-images.githubusercontent.com/6493848/35569435-1cc0ccb6-05dd-11e8-9b2e-a43d757dd81b.png)

**Comment by Kinda-me** [comment]
Разобрались, закрываю.

**Comment by BishopGIS** [comment]
А что было-то? Для базы знаний.

**Comment by Kinda-me** [comment]
Не было активировано системное приложение "Документы" (и в списке приложений оно не показывалось по умолчанию), так что не могла его найти.

Помогло вот это:

go to settings > on the bottom choose installed apps > on the top (in context menu) choose "Show all apps" > go to the bottom find Documents app (its in bottom because disabled) > enabled it with pressing enable on the bottom screen..
