### ISSUE TITLE
пропадает векторный слой из списка слоев, восстановление данных ?

### ISSUE THREAD

**Issue by ABiatov** [nextgis/android_gisapp#611]
Несколько раз, на разных планшета пропадали слои с собранными данными из списка слоев.
При этом в данных слоях содержится довольно много собранных данных.
Прикрепляемые к точкам сбора фотографии сохранились в папке "Внутреняя память/DCIM/NextGIS/"
Есть ли возможность где-то в системной папке
 "Внутреняя память/Android/data/com.nextgis.mobile/files/map/"
найти файлы относящиеся к пропавшему слою и восстановить данные?

**Comment by ABiatov** [comment]
в SQlite файле layers.db таблиц атрибутивных таблиц эти слоев тоже нет.
Есть атрибутивные таблицы к каким-то другим 2-м векторным слоям, а в списке слоев в NGM подключено 8 векторных слоев.

**Comment by ABiatov** [comment]
Пропавший векторный слой был создан из формы созданной при помощи NGFB на основании точечного слоя из nextgis.com

Но через некоторое время на веб-гис был поменян пароль зашитый в ранее созданную форму.

Вероятно при попытке синхронизации слоя с неподходящим паролем сам слой в месте с данными в нем и пропали.

**Comment by simgislab** [comment]
надо попытаться воспроизвести эту ситуацию на каком-нибудь синтетическом наборе данных

**Comment by BishopGIS** [comment]
По переданным данным ситуация следующая:
1. В базе данных есть ряд слоев (в дополнение к стандартным)
2. В файле проекта ``default.ngm`` в составе карты есть эти слои
3. А вот папок с вложениями, с пространсвенным индексом и описанием слоев - нет.

Из-за п3 и не видны эти слои. Есть еще оригинальные фотки в папке DCIM.NextGIS и DCIM/NextGIS.

Отсутсвие папко приводит к потере связи фото с записфми слоя и описаний фото (если они были).

В НГМ необходимо добавить возможность экспорта в GeoJSON не только слоев из ``default.ngm`` но и из БД напрямую (показывать имена таблиц вида ``layer_20180130141004746``) что бы пользователь мог выбрать что экспортировать.

**Comment by ABiatov** [comment]
Проблема повторилась. На этот раз пропавший слой присутствует в базе данных layers.db

Если базу данных подключить в QGIS через Менеджер БД, то видна таблица слоя и его атрибуты.

но в QGIS как векторный слой не добавляется.

Геометрия записана как BLOB в полях "_geom", "_geom_2", "_geom_4", "_geom_6",  "_geom_8", "_geom_10",  "_geom_12", "_geom_14", "_geom_16", "_geom_18". 

При этом у разных записей есть данные не во всех geom-полях.

**Как информацию про геометрию получить в текстовом виде, и при этом не потерять данные из других полей?**

**Comment by ABiatov** [comment]
пробовал добавить запросом
SELECT _id, field_63672, field_68602, field_75369, field_82068, GeometryType(GeomFromWKB(_geom )) FROM layer_202004301521234941

не получилось

**Comment by ABiatov** [comment]
пробовал добавить запросом через  DB Manager:
SELECT _id, field_63672, field_68602, field_75369, field_82068, GeometryType(GeomFromWKB(_geom )) FROM layer_202004301521234941

не получилось.

 А через "Data Source Manager" -> Браузер  добавился как таблица без геометрии.


![изображение](https://user-images.githubusercontent.com/13443276/86100462-81f51b00-bac1-11ea-801f-d7f699c21cc2.png)


Я верно понял, что в поле _geom геометрия в формате WKB?

**Comment by simgislab** [comment]
Новый инструмент 
Настройки - Карта - Восстановить потерянные слои
