### ISSUE TITLE
Remove a check that disallows editing of a PostGIS layer proxied by NGW

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#619]
от Димы
> Мне кажется нет - была добавлена проверка на постгис когда НГВ не поддерживало редактирование слоев из него.

от Дениса

> http://beitsahourmunicipality.nextgis.com/api/resource/103

```
interfaces: [
"IFeatureLayer",
"IWritableFeatureLayer"
]
```

IWritableFeatureLayer - вот раньше его не было, теперь появился

> Rykov Denis, [03.04.18 11:17]
а вот не надо использоват типы слоёв, а нужно использовать интерфейсы, тогда бы и не было такой проблемы

**Comment by BishopGIS** [comment]
К сожалению в АПИ доках по поводу IWritableFeatureLayer не отражено.
