### ISSUE TITLE
Missing share options

### ISSUE THREAD

**Issue by bobombolo** [nextgis/android_gisapp#620]
Reading the documentation (http://docs.nextgis.com/docs_ngmobile/source/share.html ) it states "You can save the file on a memory card." but I see no such option. In fact I also only see 4 options for "share". I see "Wi-Fi Direct", "Bluetooth", "Gmail" and "Messaging". Unlike any other android app when I hit share I have many other options including the default messaging app I have installed which is NOT "Messaging", Hangouts, etc.

**Comment by BishopGIS** [comment]
Share menu items depend on installed in your Android phone applications. You need some application (i.e. [ez explorer](https://play.google.com/store/apps/details?id=com.estrongs.android.pop)) which add this item to share menu.
