### ISSUE TITLE
Update to 2.5.7.1 breaks uploads to private NextGIS server

### ISSUE THREAD

**Issue by Cthulhu-Dreams** [nextgis/android_gisapp#626]
Recently collected field data was not appearing on our server, **despite the app reporting a successful sync.**  Upon troubleshooting the app, I discovered I was unable to connect to our server via the "Add from Web GIS" layer addition option.  Unsure if this was a credentials issue, I attempted to change the username and password for the Web GIS account - only to receive an error saying the URL is invalid.

I then check to see if I had the latest update to the app - I noticed URL validation was added with 2.5.7.1. Suspecting this is the issue, I found a tablet that had not been updated and was able to successfully connect to our private server using the same credentials found on the tablet that could not connect.

I then updated the functional tablet to 2.5.7.1 and it could no longer connect to our private server.  I am not sure why our server URL would be rejected - perhaps because it includes the port number?

**Comment by 4eRTuk** [comment]
Should be fixed in https://github.com/nextgis/android_gisapp/commit/85ca7c410747680a177579fdb1642a67895fc71f
