### ISSUE TITLE
Если не дать разрешение на доступ к контактам, то приложение вылетает при "добавить геосервис"

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#630]
Если не дать разрешение на доступ к контактам, то приложение вылетает при "добавить геосервис".
Android

**Comment by BishopGIS** [comment]
Похоже вот это падение - https://sentry.nextgis.com/nextgis/nextgis-mobile/issues/1587/

**Comment by trolleway** [comment]
Так же вылетает при добавлении полей в диалоге создания слоя

**Comment by BishopGIS** [comment]
Вот еще одно аналогичное - https://sentry.nextgis.com/nextgis/nextgis-mobile/issues/1590/
