### ISSUE TITLE
Support measure distance control

### ISSUE THREAD

**Issue by simgislab** [nextgis/android_gisapp#633]
grey text field + a refresh button

text field shows distance between current position of the point and current position of the surveyor in meters

distance calculates on form initializing - when point is created. Distance IS NOT updated if point is edited. <- to discuss May be can update always if position of the point is shifted in respect of the previous position.

refresh button forces update of the calculation

See also https://github.com/nextgis/formbuilder/issues/121

**Comment by 4eRTuk** [comment]
Implemented in 610f64105dc033e4db4550f7bc2dea58e31924b6
