### ISSUE TITLE
Проблема с  экспортом точечного слоя

### ISSUE THREAD

**Issue by Saltuarius** [nextgis/android_gisapp#635]
v. 2.5.7.7 (rev.43)

Точечный слой (около 40 точек в слое) невозможно экспортировать на любые облачные сервисы или локальное хранилище устройства. При выборе опции "Поделиться" в меню слоя и при попытке куда-либо его отправить выдает ошибку "Unsupported content type". Ошибка повторяется при выборе 
любых точечных слоев с разным количеством точек и фото (или их отсутствием).

**Comment by 4eRTuk** [comment]
Fix in 10f178bfe5ab60b8416a44741cd6cdd1f6ae1973
