### ISSUE TITLE
Настройка вида растрового слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#64]
Возможность выбора способа отображения: ч/б, инверсия, яркость, контраст.
Возможно инверсию привязать к пункту "ночной режим" - нужно такое?

**Comment by BishopGIS** [comment]
Сделано все кроме инверсии

**Comment by simgislab** [comment]
>Возможно инверсию привязать к пункту "ночной режим" - нужно такое? 
пока не обязательно

**Comment by simgislab** [comment]
закрываю как сделано.
