### ISSUE TITLE
Не сохраняются данные при наличии в форме элементов вокруг виджета Табы

### ISSUE THREAD

**Issue by MikhanGusev** [nextgis/android_gisapp#640]
Если вокруг виджета "Табы" в форме есть другие элементы - форма не даёт сохранить данные при нажатии на галку в правом верхнем углу. Если "Табы" не окружены другими элементами - данные сохраняются. Пример формы: 
[Reptile Survey Test do not use (2).zip](https://github.com/nextgis/android_gisapp/files/3003796/Reptile.Survey.Test.do.not.use.2.zip)

**Comment by 4eRTuk** [comment]
Данные сне сохранялись из-за пустого сдвоенного списка. Плюс если не указать значения в выпадающем списке, у которого не стоит галочка "Свои значения"
