### ISSUE TITLE
Добавить фильтрацию трека

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#65]
В ходе записи координат есть явно ошибочные выбросы. Необходимо фильтровать такие данные.

**Comment by BishopGIS** [comment]
В ходе тестирование на выбросы поигрались с минимальным расстоянием записи координат. При больших значениях - через 25 и более метров выбросов нет. Необходимо дополнительно проверить эту гипотезу в городской застройке и в лесу. Есть предположение, что алгоритм сглаживания уже есть в ОС, просто когда программа запрашивает точки очень часто, то алгоритм работать не может (нет статистики). Если гипотеза подтвердится, предлагаю ограничить минимальное расстояние 15 м и минимальное время 5 сек. 
А для точного снятия координат будет отдельный функционал из старого приложения (там где накапливается статистика и считается усредненные координаты и оценка их точности по критерию СЕ)

**Comment by BishopGIS** [comment]
Переоткрыть если будет подтверждение, что ОС не округляет координаты

**Comment by simgislab** [comment]
а по умолчанию у нас сейчас стоит округление? Если нет, то надо поставить, иначе это будет очень угнетать нового пользователя, пока он не догадается это сделать.

**Comment by BishopGIS** [comment]
Такое можно сделать ограничив порог или выставив умолчальные значения выше возможных - например 5 с и 15 м. Сейчас стоит 0с и 1м. Изменить значения или ввести ограничение?

**Comment by simgislab** [comment]
я не понял разницы, так или иначе, главное чтобы не появлялось этих ужасных выбросов

**Comment by BishopGIS** [comment]
Все очень просто: есть ситуация - городить свой алгоритм или полагаться на систему. Мы провели ряд экспериментов и считаем что система фильтрует выбросы сама, если дать ей запас по точкам. Т.е. если мы просим выдавать точки как можно чаще - система так и делает, а если частота или расстояние позволяют накопить какую-то статистику, то происходит фильтрация.
У нас можно сделать 2 вещи:
1. Ограничить значение по времени и расстоянию до 5 с и 15 м
2. Не ограничивать, но по-умолчанию выставить те самые 5 с и 15 м.

Вопрос, как лучше сделать: 1 или 2? Возможно есть 3?

**Comment by simgislab** [comment]
я все-таки не понимаю откуда берутся такие выбросы, я никогда не видел их ни на одной модели гпс-ов

**Comment by BishopGIS** [comment]
Какое отношение вопрос имеет к тикету? Выбросы есть - это факт. Решение предложено. Остальное к Гуглу.

**Comment by simgislab** [comment]
нужно выставить значение по умолчанию, чтобы из коробки выбросов не было

**Comment by simgislab** [comment]
про выбросы см. #132, если это решит проблему, то цифры по умолчанию нужно вернуть к 0,0

**Comment by BishopGIS** [comment]
А зачем такие именно цифры в умолчании? Для автомобиля, самолета, поезда - так часто вредно - у нас слой при отрисовке не фильтрует экстент и при большом количестве точек жутко тормозит - Руслан уже это показывал.
Кому надо 0,0 пусть потрудится зайти в настройки и исправить. Абсолютно не вижу, что большому количеству народа нужно так часто точки в треке.

**Comment by simgislab** [comment]
ну ок, ну 2 с поставь и 5 метров, но то, что сейчас по умолчанию - точно не годится для пешеходных треков.

Это если проблема с выбросами таки решится, пока не понятно, решится ли. @4eRTuk как там с этим?

**Comment by simgislab** [comment]
Выбросы таки присутствуют, даже если в треках стоит только GPS и это большой косяк

![](http://m-d.me/img/ss/20153713-163728.png)

Переоткрываю и ставлю пока 2.4, но хорошо бы в 2.3 починить все-таки

**Comment by KolesovDmitry** [comment]
Короткого ответа не получилось, пришлось написать подробно с формулами и кодом. Для того, чтобы его было удобнее смотреть - выложил [отрисованую версию сюда](https://nbviewer.jupyter.org/gist/KolesovDmitry/51900b4366ae87de456abb176568d1c5)


В двух словах - отфильтровать не слишком вычислительно затратными методами можно, но (не исключено, что) придется еще немного поэкспериментировать: надо смотреть на конкретные нужды.
