### ISSUE TITLE
Не отображаются контролы при утсановке "Ввод с поиском" -> true

### ISSUE THREAD

**Issue by MikhanGusev** [nextgis/android_gisapp#653]
NextGIS Mobile, v. 2.6.10 (rev. 67). При попытке начать сбор с формой, где есть контрол "Выпадающий список" с установленной опцией "Ввод с поиском" форма открывается, но контролы после первого такого не отображаются. Пример формы: 
[Насаждения.zip](https://github.com/nextgis/android_gisapp/files/4466010/default.zip)

**Comment by 4eRTuk** [comment]
Исправлено в 5a95b7bcf7a3f06861eee1ed1bca4f30879e67b7
