### ISSUE TITLE
Ошибка экспорта слоев с полигонами в NGM (загруженных локально через форму .ngfp)

### ISSUE THREAD

**Issue by Romchik93** [nextgis/android_gisapp#654]
Кейс:
1. Создаю NextGis Formbuilder Структуру таблицы
2. Сохраняю на планшет
3. Создаю слой из локального шаблона в NGM
4. Создаю необходимые объекты, заполняю их таблицы
5. Нажимаю поделится и пишет ошибку - невозможно создать конечный geojson

[Куртины.zip](https://github.com/nextgis/android_gisapp/files/4521281/default.zip)

**Comment by 4eRTuk** [comment]
Fix in 2925fbf4cb6a95319ad064a2b1fa9ff4c389b84e
