### ISSUE TITLE
Проблема с удалением слоев из NextGIS Mobile

### ISSUE THREAD

**Issue by Romchik93** [nextgis/android_gisapp#655]
Кейс от клиента:
"удаляю, закрываю программу, открываю по новой, и слои всё по-прежнему там же. не помогает даже перезагрузка телефона."
Видео - https://yadi.sk/i/GNLWs3lfk2pbnw

Тикет - https://support.nextgis.com/#ticket/zoom/288

**Comment by Romchik93** [comment]
https://support.nextgis.com/api/v1/ticket_attachment/287/1559/2487?view=inline
https://support.nextgis.com/api/v1/ticket_attachment/287/1559/2488?view=inline

**Comment by simgislab** [comment]
Видео

https://t.me/nextgis_chat/12022
https://t.me/nextgis_chat/12025
https://t.me/nextgis_chat/12040

**Comment by 4eRTuk** [comment]
Исправлено в последней версии
