### ISSUE TITLE
Не показываются длинные названия полей и содержимое таблицы атрибутов в NGM

### ISSUE THREAD

**Issue by Romchik93** [nextgis/android_gisapp#656]
Если названия достаточно длинные

Пример от клиента:
https://support.nextgis.com/api/v1/ticket_attachment/287/1559/2490?view=inline
https://support.nextgis.com/api/v1/ticket_attachment/287/1559/2489?view=inline

И снял видео - https://yadi.sk/i/GNLWs3lfk2pbnw

Тикет - https://support.nextgis.com/#ticket/zoom/289

**Comment by simgislab** [comment]
надо запросить воспроизводится ли на других устройствах

**Comment by 4eRTuk** [comment]
воспроизводится, не надо уточнять. я чиню
