### ISSUE TITLE
Проверка топологии при редактировании

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#70]
Исправление самопересечений (бабочка в полигоне), выход дырок за границу полигона и т.п.

**Comment by 4eRTuk** [comment]
Какое ожидаемое поведение? Запрет сохранения и выводить диалог/toast?

**Comment by simgislab** [comment]
да, не давать сохранять для начала и сообщение

**Comment by 4eRTuk** [comment]
Какие еще ограничения есть? Пересечение нескольких дырок внутри полигона?

**Comment by BishopGIS** [comment]
Да, и видимо пока все.
