### ISSUE TITLE
No resource found that matches the given name ('@drawable/...')

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/android_gisapp#71]
Кто-то забыл добавить картинки на гитхаб в maplibui
```
@drawable/abc_ic_menu_selectall_mtrl_alpha
@drawable/ic_visibility_white_24dp
@drawable/ic_visibility_off_white_24dp
```
и возможно
```
@drawable/abc_ic_menu_share_mtrl_alpha
```
из закомментированного кода.

**Comment by 4eRTuk** [comment]
Ой, да :)
Все abc_xxx в AppCompat есть.

**Comment by NikitaFeodonit** [comment]
> Все abc_xxx в AppCompat есть.

Да, после пересборки проекта перестало на abc_xxx спотыкаться.
