### ISSUE TITLE
Additional layer info

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#72]
В диалоге настроек слоя показывать информацию о слое:
1. Тип геометрии
2. Тип слоя
3. Структура (названия и типы полей)
4. Наличие форм
5. Другая информация специфичная слою

**Comment by BishopGIS** [comment]
В настройки слоя добавил тип геометрии и количество записей.

**Comment by simgislab** [comment]
6. Источник

**Comment by 4eRTuk** [comment]
Может быть тип в заголовок окна, а количество записей в подзаголовок?

**Comment by BishopGIS** [comment]
Да, хорошая идея
