### ISSUE TITLE
При отображении трека в начале и в конце ставить отметки

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#75]
При отображении треков (за исключением текущего) в начале и в конце трека ставить отметки: зеленый и красный кружок с цифрой сессии или без цифры (надо посмотреть как понятнее).

**Comment by 4eRTuk** [comment]
Стоит ли добавлять номер сессии? Сейчас он нигде не упоминается для пользователя.

**Comment by BishopGIS** [comment]
Я думаю пока не стоит. Просто пользователь должен выключить все не нужные ему треки.

**Comment by 4eRTuk** [comment]
Ага, думаю #171 вполне будет достаточно в ближайшем будущем.

**Comment by simgislab** [comment]
можно побольше маркеры сделать, сейчас их что-то совершенно не видно, пока не увеличишь до упора? И еще какие-то артефакты при отрисовке.

https://www.dropbox.com/s/5xqvwic2t5igbpi/Screenshot_2015-12-13-14-12-59.png?dl=0

**Comment by BishopGIS** [comment]
Да лучше маркеры сделать картинками, тогда с размером не надо парится. 
http://romannurik.github.io/AndroidAssetStudio/icons-actionbar.html#source.type=clipart&source.space.trim=0&source.space.pad=0&source.clipart=res%2Fclipart%2Ficons%2Fcontent_flag.svg&name=ic_action_content_flag&theme=light&color=33b5e5%2C60

Красный и зеленый

**Comment by BishopGIS** [comment]
И опять выбросы!!!

**Comment by simgislab** [comment]
да, https://github.com/nextgis/android_gisapp/issues/65
