### ISSUE TITLE
Перенести название таблицы в заголовок окна атрибутов

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#78]
Туда же добавить общее количество и текущую запись
```
X Случайные то... (3 из 50)
``` 
Также выделить синим цветом (как сделано в дереве слоев)

**Comment by 4eRTuk** [comment]
Ты имеешь ввиду в тулбар? Длинные названия обрезаться будут тогда. А что выделять синим?

**Comment by BishopGIS** [comment]
Xто-то типа такого:
![screenshot_2016-02-04-15-06-50](https://cloud.githubusercontent.com/assets/1708122/12814676/f373dca8-cb51-11e5-86ab-0456c7cfd70e.png)
