### ISSUE TITLE
Добавить "объясняющий" экран на первый запуск

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#8]
- http://stackoverflow.com/questions/18476088/how-do-i-create-the-semi-transparent-grey-tutorial-overlay-in-android
- https://github.com/amlcurran/ShowcaseView

**Comment by simgislab** [comment]
Еще есть тултипы @4eRTuk такие делал для метро, они менее массивные и инвазивные как onboard (кстати вроде так правильно эти экраны называются, http://www.smashingmagazine.com/2014/08/11/mobile-onboarding-beginners-guide/)

**Comment by 4eRTuk** [comment]
Вот еще вариант: https://github.com/PaoloRotolo/AppIntro
Позволяет сразу сделать запрос всех нужных разрешений для 6.0.

**Comment by simgislab** [comment]
для меня вопрос что мы на нем хотим показывать

**Comment by BishopGIS** [comment]
Простые вещи, типа тут слои, тут кнопка добавления геометри, так загрузить данные, тут включить +/-

**Comment by simgislab** [comment]
на одном экране оно не поместится

**Comment by BishopGIS** [comment]
@simgislab @4eRTuk мне кажется текущая версия приложения обладает таким экраном. Предлагаю закрыть.

**Comment by simgislab** [comment]
так точно, содержание оного - отдельный вопрос, новые ишьюсы
