### ISSUE TITLE
Отмена добавления объекта на карте.

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#82]
Нажимаю кнопку "Добавить объект на карте" - выбираю слой - добавляю точку.
Передумал добавлять точку, но отменить режим ввода невозможно. 
В левом-нижнем углу есть кнопка "сохранить", логично рядом с ней добавить кнопку "отменить"

**Comment by BishopGIS** [comment]
Отмена происходит по нажатию в любой области экрана. Слева можно поставить только одну кнопку. Можно добавить справа, но будет путаться с кнопкой удалить.

**Comment by BishopGIS** [comment]
Приняли решение добавить крестик как первой кнопкой в тулбаре
