### ISSUE TITLE
Нет диалога выбора слоя для редактировании при добавлении текущей точки

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#83]
При добавлении объекта на карте идёт диалог выбора слоя, а при добавлении объекта по текущим координатам - диалога нет.
ASUS Nexus 7

**Comment by BishopGIS** [comment]
Диалог появляется когда есть выбор. Если слой один (в данном случае текущее местоположение добавляет точку к точечному слою, который всего один), то действие применяется сразу к нему. Во всплывающем сообщении (Toast) об этом выдается уведомление.

**Comment by trolleway** [comment]
Эээ, в каком именно уведомлении? Я его не видел.

**Comment by BishopGIS** [comment]
Toast - всплывающее сообщение. Не видел, ну тут либо ошибка, или не заметил. У меня всплывает.
