### ISSUE TITLE
Не добавляется значение с контрола дата-время

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#86]
Делаю форму с тремя пикерами: дата, время, дата-время.
Открываю форму. В трёх полях стоит 1970-01-01.
Открываю все пикеры, и нажимаю кнопку ОК. 
Из пикеров даты и времени берётся значение текущего времени, а из пикера дата-время значение не берётся, и в поле остаётся 1970-01-01

**Comment by BishopGIS** [comment]
Проявляетя на Android 5, у меня на 4 работает
