### ISSUE TITLE
Добавить оверлей со шкалой масштаба

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#94]
Шкала, zoom level (в зависимости от настроек). Отображается только при касании или изменении зума потом плавно исчезает.

**Comment by taimyr** [comment]
По моему, лучше пусть не исчезает, а включается-выключается через настройки (как кнопки зума)

**Comment by BishopGIS** [comment]
Рослесзащита поделилась кодом:
https://drive.google.com/file/d/0BzlLlHyrgQHkc1hKdV9Jb3dZTWs/view?usp=sharing
https://drive.google.com/file/d/0BzlLlHyrgQHkMnhSV2I5MHdSeHM/view?usp=sharing

**Comment by 4eRTuk** [comment]
Опять же, где расположить шкалу? Может справа по краю чуть выше FAB?

**Comment by simgislab** [comment]
я бы тоже вверху справа показывал, и перекрывал бы ее полем с цифрами если идет измерение расстояния инструментом, как например

**Comment by 4eRTuk** [comment]
Добавил слева вниз пока, вроде неплохо вписывется.

**Comment by simgislab** [comment]
а где оно? не видно в свежей сборке что-то

**Comment by 4eRTuk** [comment]
Подмодули не обновились, надо пересобрать.

**Comment by simgislab** [comment]
думаю лучше округлить километраж, доли не нужны
