### ISSUE TITLE
Индикация процесса синхронизации

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#99]
В статусе отображать прогресс с загрузкой

**Comment by 4eRTuk** [comment]
Это при синхронизации с NGW через кнопку в боковом меню?

**Comment by BishopGIS** [comment]
Нет, это сделано. Еще надо в статусбаре показывать (но в настройках выключить по-умолчанию).

**Comment by 4eRTuk** [comment]
Я про то, что когда в фоне синхронизация, то наверное не стоит показывать. Или стоит?

**Comment by BishopGIS** [comment]
Вот как раз попросили показывать. 
Поэтому я и предложил показывать или не показывать вынести в настройки, и сделать "не показывать" по-умолчанию.

**Comment by BishopGIS** [comment]
В лесном инспекторе сделана индикация так как надо. Там правда нет настройки для отключения показа.
